"""Kernel / network tuning profile (SPEC §22.6): RAM-scaled socket-buffer and conntrack limits written
to /etc/sysctl.d/999-pcdn.mem.conf (`pcdn-agent tune --write`, install.sh), and the runtime check of
every tuned value (sysctl files vs PROC_SYS, congestion control, qdisc, nginx open-file limit) that the
heartbeat reports as `tuning`."""

import json
import os
import re
import shutil
import subprocess
import time

from .common import default_iface
from .settings import log

GIB = 1024 ** 3
MIB = 1024 ** 2
BASE_FILE = "999-pcdn.conf"            # install.sh's static base (sorted before the mem file)
# this module's RAM-scaled overrides. SPEC §22.6 calls it 999-pcdn-mem.conf, but "-" sorts before "." so
# that name would load BEFORE 999-pcdn.conf (and be overridden by it at boot); "999-pcdn.mem.conf"
# sorts after both 999-pcdn.conf and 999-pcdn-conntrack.conf, which is what the SPEC asks for.
MEM_FILE = "999-pcdn.mem.conf"
CONNTRACK_FILE = "999-pcdn-conntrack.conf"
TUNING_MISMATCH_MAX = 20
TUNING_VALUE_MAX = 64
TUNING_CHECK_EVERY = 3600              # s between runtime checks (and once at start)


def ram_bytes(meminfo: str = "/proc/meminfo") -> int:
    """MemTotal in bytes (0 when unreadable)."""
    try:
        with open(meminfo) as f:
            for line in f:
                if line.startswith("MemTotal:"):
                    return int(line.split()[1]) * 1024
    except (OSError, ValueError, IndexError):
        pass
    return 0


def profile(ram: int) -> dict:
    """The RAM-scaled sysctl values (SPEC §22.6 table): < 2 GiB 8 MiB buffers / 262144 conntrack,
    2-8 GiB 32 MiB / 524288, >= 8 GiB 64 MiB / 1048576 (the static base values)."""
    if ram < 2 * GIB:
        buf, ct = 8 * MIB, 262144
    elif ram < 8 * GIB:
        buf, ct = 32 * MIB, 524288
    else:
        buf, ct = 64 * MIB, 1048576
    return {"net.core.rmem_max": str(buf), "net.core.wmem_max": str(buf),
            "net.ipv4.tcp_rmem": f"4096 131072 {buf}", "net.ipv4.tcp_wmem": f"4096 65536 {buf}",
            "net.netfilter.nf_conntrack_max": str(ct), "net.ipv4.tcp_notsent_lowat": "131072"}


def tune_enabled(cfg: dict) -> bool:
    return str(cfg.get("TUNE_PROFILE") or "auto").lower() != "off"


def mem_file_text(values: dict, ram: int) -> str:
    return ("# pcdn RAM-scaled tuning (SPEC §22.6) - generated by `pcdn-agent tune --write`, do not edit\n"
            f"# MemTotal {ram // MIB} MiB; overrides these keys of {BASE_FILE}\n"
            + "".join(f"{k} = {v}\n" for k, v in values.items()))


def write_profile(cfg: dict, run=subprocess.run) -> dict:
    """`tune --write`: write SYSCTL_DIR/999-pcdn.mem.conf when its content changes (idempotent) and load
    it with `sysctl -p`; TUNE_PROFILE=off removes it. -> {"file", "changed", "removed", "values"}."""
    d = cfg.get("SYSCTL_DIR") or "/etc/sysctl.d"
    path = os.path.join(d, MEM_FILE)
    if not tune_enabled(cfg):
        removed = False
        for stale in (path, os.path.join(d, "999-pcdn-mem.conf")):
            if os.path.exists(stale):
                os.remove(stale)
                removed = True
        return {"file": path, "changed": False, "removed": removed, "values": {}}
    ram = ram_bytes(cfg.get("PROC_MEMINFO", "/proc/meminfo"))
    values = profile(ram)
    text = mem_file_text(values, ram)
    try:
        with open(path) as f:
            changed = f.read() != text
    except OSError:
        changed = True
    if changed:
        os.makedirs(d, exist_ok=True)
        tmp = path + ".tmp"
        with open(tmp, "w") as f:
            f.write(text)
        os.chmod(tmp, 0o644)
        os.replace(tmp, path)
    if shutil.which("sysctl") and run is not None:
        try:
            run(["sysctl", "-q", "-p", path], capture_output=True, text=True, timeout=30)
        except (OSError, subprocess.SubprocessError) as e:
            log.warning("tune: sysctl -p %s failed: %s", path, e)
    return {"file": path, "changed": changed, "removed": False, "values": values}


_KV = re.compile(r"^\s*([a-z0-9_.]+)\s*=\s*(.*?)\s*$")


def read_sysctl_file(path: str) -> dict:
    """{key: value} of a sysctl.d file (comments / blank lines skipped; whitespace normalised)."""
    out = {}
    try:
        with open(path) as f:
            for line in f:
                if line.lstrip().startswith(("#", ";")):
                    continue
                m = _KV.match(line)
                if m:
                    out[m.group(1)] = " ".join(m.group(2).split())
    except OSError:
        pass
    return out


def read_proc_sys(proc_sys: str, key: str) -> str | None:
    try:
        with open(os.path.join(proc_sys, *key.split("."))) as f:
            return " ".join(f.read().split())
    except OSError:
        return None


def nginx_nofile(cfg: dict) -> int | None:
    """Soft `Max open files` of the nginx master (pid from NGINX_PID_FILE, limits under PROC_DIR)."""
    try:
        with open(cfg.get("NGINX_PID_FILE") or "/run/nginx.pid") as f:
            pid = int(f.read().strip())
        with open(os.path.join(cfg.get("PROC_DIR", "/proc"), str(pid), "limits")) as f:
            for line in f:
                if line.startswith("Max open files"):
                    v = line[len("Max open files"):].split()[0]
                    return None if v == "unlimited" else int(v)
    except (OSError, ValueError, IndexError):
        pass
    return None


def iface_qdisc(iface: str | None, run=subprocess.run) -> str | None:
    """Root qdisc kind of the default interface (`tc qdisc show dev`), None without tc / interface."""
    if not iface or not shutil.which("tc"):
        return None
    try:
        p = run(["tc", "qdisc", "show", "dev", iface], capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.SubprocessError):
        return None
    for line in (p.stdout or "").splitlines():
        parts = line.split()
        if len(parts) > 1 and parts[0] == "qdisc" and " root " in f" {line} ":
            return parts[1][:TUNING_VALUE_MAX]
    return None


def check_tuning(cfg: dict, run=subprocess.run) -> dict:
    """The heartbeat `tuning` object: expected (999-pcdn.conf + conntrack file + 999-pcdn.mem.conf) vs
    actual (PROC_SYS) for every key, the congestion control (and bbr availability when TCP_CC=bbr), the
    default qdisc vs the qdisc on the default interface, and the nginx master's open-file limit. Keys whose
    /proc/sys entry does not exist (module not loaded) cannot be verified and are skipped."""
    d = cfg.get("SYSCTL_DIR") or "/etc/sysctl.d"
    proc_sys = cfg.get("PROC_SYS") or "/proc/sys"
    want = {}
    want.update(read_sysctl_file(os.path.join(d, BASE_FILE)))
    want.update(read_sysctl_file(os.path.join(d, CONNTRACK_FILE)))
    if tune_enabled(cfg):
        want.update(read_sysctl_file(os.path.join(d, MEM_FILE)))
    mism = []

    def bad(key, w, h):
        if len(mism) < TUNING_MISMATCH_MAX:
            mism.append({"key": key[:TUNING_VALUE_MAX], "want": str(w)[:TUNING_VALUE_MAX],
                         "have": str(h)[:TUNING_VALUE_MAX]})

    for key in sorted(want):
        have = read_proc_sys(proc_sys, key)
        if have is not None and have != want[key]:
            bad(key, want[key], have)
    cc = read_proc_sys(proc_sys, "net.ipv4.tcp_congestion_control")
    if str(cfg.get("TCP_CC") or "").lower() == "bbr":
        avail = read_proc_sys(proc_sys, "net.ipv4.tcp_available_congestion_control")
        if avail is not None and "bbr" not in avail.split():
            bad("net.ipv4.tcp_available_congestion_control", "bbr", avail)
    default_qdisc = read_proc_sys(proc_sys, "net.core.default_qdisc")
    qdisc = iface_qdisc(default_iface(cfg.get("PROC_ROUTE", "/proc/net/route")), run)
    if qdisc and default_qdisc and qdisc not in (default_qdisc, "mq"):
        bad("qdisc", default_qdisc, qdisc)   # mq: per-queue children carry the default qdisc
    return {"profile": "auto" if tune_enabled(cfg) else "off",
            "ram_mb": ram_bytes(cfg.get("PROC_MEMINFO", "/proc/meminfo")) // MIB,
            "ok": not mism, "cc": cc[:TUNING_VALUE_MAX] if cc else None, "qdisc": qdisc,
            "nofile": nginx_nofile(cfg), "mismatches": mism}


class TuningCheck:
    """Caches check_tuning for TUNING_CHECK_EVERY seconds (cheap reads, but not every heartbeat)."""

    def __init__(self, cfg: dict):
        self.cfg = cfg
        self.at = 0.0
        self.value: dict | None = None

    def get(self, now: float | None = None) -> dict | None:
        now = time.monotonic() if now is None else now
        if self.value is None or now - self.at >= TUNING_CHECK_EVERY:
            try:
                self.value = check_tuning(self.cfg)
            except Exception as e:  # noqa: BLE001 - informational only
                log.debug("tuning check: %s", e)
                self.value = None
            self.at = now
        return self.value


def tune_main(cfg: dict, args: list) -> int:
    """`pcdn-agent tune [--write|--check]` (default --check): prints JSON."""
    if "--write" in args:
        res = write_profile(cfg)
        print(json.dumps(res, indent=1, sort_keys=True))
        return 0
    ram = ram_bytes(cfg.get("PROC_MEMINFO", "/proc/meminfo"))
    print(json.dumps({"profile_values": profile(ram) if tune_enabled(cfg) else {}, "check": check_tuning(cfg)},
                     indent=1, sort_keys=True))
    return 0
