"""nftables rulesets: the host network guard (install.sh --harden-net, SPEC §16.3) and the
connect-time origin guard (install.sh, default on)."""

import ipaddress
import os
import re
import socket
import urllib.parse

from ..common import _int, default_iface
from ..settings import log
from ..validation.origin import internal_ports, internal_src, origin_private_allow
from .stream import l4_port_range


# ----------------------------------------------------------------- host network guard (SPEC §16.3)

GUARD_TABLE = "pcdn_guard"


def _guard_int(cfg: dict, key: str, default: int, lo: int, hi: int) -> int:
    return _int(cfg.get(key), default, lo, hi)


def guard_allow(cfg: dict, resolve=socket.getaddrinfo) -> tuple[list[str], list[str]]:
    """Never-limited sources: the controller's addresses (resolved now from CONTROLLER_URL) and
    GUARD_ALLOW. -> (ipv4 cidrs, ipv6 cidrs)."""
    nets = []
    host = urllib.parse.urlparse(cfg.get("CONTROLLER_URL") or "").hostname
    if host:
        try:
            nets += [ai[4][0] for ai in resolve(host, None)]
        except (OSError, UnicodeError):
            log.warning("guard: cannot resolve the controller %s; only GUARD_ALLOW is allow-listed", host)
    nets += re.split(r"[\s,]+", str(cfg.get("GUARD_ALLOW") or "").strip())
    v4, v6 = [], []
    for n in nets:
        try:
            net = ipaddress.ip_network(str(n).strip().split("%")[0], strict=False)
        except ValueError:
            continue
        (v4 if net.version == 4 else v6).append(str(net))
    return sorted(set(v4)), sorted(set(v6))


def tcp_wscale(proc: str = "/proc/sys") -> int:
    """The window-scale shift Linux advertises (tcp_select_initial_window over max(tcp_rmem[2],
    rmem_max)): the SYN proxy must announce the same value the server socket uses."""
    try:
        with open(os.path.join(proc, "net/ipv4/tcp_rmem")) as f:
            space = int(f.read().split()[2])
        with open(os.path.join(proc, "net/core/rmem_max")) as f:
            space = max(space, int(f.read().strip()))
    except (OSError, ValueError, IndexError):
        return 7
    ws = 0
    while space > 65535 and ws < 14:
        space >>= 1
        ws += 1
    return ws


def iface_mtu(iface: str | None, sys_net: str = "/sys/class/net") -> int:
    try:
        with open(os.path.join(sys_net, iface or "-", "mtu")) as f:
            return max(576, min(65535, int(f.read().strip())))
    except (OSError, ValueError):
        return 1500


def render_guard(cfg: dict, synproxy: bool = False, allow: tuple | None = None, wscale: int | None = None,
                 mtu: int | None = None) -> str:
    """nftables ruleset for install.sh --harden-net (SPEC §16.3), table inet pcdn_guard, loaded
    atomically (the leading "table/delete" pair replaces a previous version in one transaction).
    Policy accept everywhere: the guard only drops over-limit / invalid packets. Order: loopback,
    SSH ports and the allow-list (controller + GUARD_ALLOW) are accepted FIRST, so they are never
    limited; then optionally the SYN proxy for the HTTP(S) ports, invalid conntrack state, per-/24
    (IPv6 /64) and global SYN limits, per-source UDP/<HTTPS_PORT> (QUIC) limit and an ICMP echo
    limit. Complements, never replaces, datacenter scrubbing."""
    v4, v6 = allow if allow is not None else guard_allow(cfg)
    ssh = sorted({int(x) for x in re.findall(r"\d{1,5}", str(cfg.get("GUARD_SSH_PORTS") or "22"))
                  if 0 < int(x) < 65536} or {22})
    http_port = _int(cfg.get("HTTP_PORT"), 80, 1, 65535)
    https_port = _int(cfg.get("HTTPS_PORT"), 443, 1, 65535)
    syn = _guard_int(cfg, "GUARD_SYN_RATE", 1000, 1, 10_000_000)
    burst = _guard_int(cfg, "GUARD_SYN_BURST", 2000, 1, 10_000_000)
    glob = _guard_int(cfg, "GUARD_SYN_GLOBAL", 50000, 1, 100_000_000)
    udp = _guard_int(cfg, "GUARD_UDP_RATE", 20000, 1, 100_000_000)
    icmp = _guard_int(cfg, "GUARD_ICMP_RATE", 100, 1, 10_000_000)
    ws = tcp_wscale() if wscale is None else wscale
    mtu = iface_mtu(default_iface()) if mtu is None else mtu
    web = f"{{ {http_port}, {https_port} }}"
    synf = "tcp flags & (fin|syn|rst|ack) == syn"

    def aset(name, typ, elems):
        body = f"    set {name} {{\n        type {typ}\n        flags interval\n"
        if elems:
            body += "        elements = { " + ", ".join(elems) + " }\n"
        return body + "    }"

    def dset(name, typ):
        return (f"    set {name} {{\n        type {typ}\n        flags dynamic, timeout\n        timeout 60s\n"
                f"        size 65535\n    }}")

    out = ["# pcdn host network guard (SPEC §16.3) — generated by `pcdn-agent guard`, do not edit.",
           f"# Remove with: install.sh --no-harden-net (or: nft delete table inet {GUARD_TABLE})",
           f"table inet {GUARD_TABLE} {{}}", f"delete table inet {GUARD_TABLE}", f"table inet {GUARD_TABLE} {{",
           aset("allow4", "ipv4_addr", v4), aset("allow6", "ipv6_addr", v6),
           dset("syn4", "ipv4_addr"), dset("syn6", "ipv6_addr"), dset("udp4", "ipv4_addr"), dset("udp6", "ipv6_addr")]
    if synproxy:
        out += ["    chain raw {", "        type filter hook prerouting priority raw; policy accept;",
                f"        tcp dport {web} {synf} notrack", "    }"]
    rules = ['iif "lo" accept',
             f"tcp dport {{ {', '.join(str(p) for p in ssh)} }} accept",
             "ip saddr @allow4 accept", "ip6 saddr @allow6 accept",
             # per-source /24 (IPv6 /64) and host-wide new-connection rates
             f"{synf} update @syn4 {{ ip saddr & 255.255.255.0 limit rate over {syn}/second burst {burst} packets }} drop",
             f"{synf} update @syn6 {{ ip6 saddr & ffff:ffff:ffff:ffff:: limit rate over {syn}/second burst {burst} packets }} drop"]
    if synproxy:
        rules += [f"meta nfproto ipv4 tcp dport {web} ct state invalid,untracked synproxy mss {mtu - 40} wscale {ws} timestamp sack-perm",
                  f"meta nfproto ipv6 tcp dport {web} ct state invalid,untracked synproxy mss {mtu - 60} wscale {ws} timestamp sack-perm"]
    rules += ["ct state invalid drop",
              f"{synf} limit rate over {glob}/second burst {glob * 2} packets drop",
              f"udp dport {https_port} update @udp4 {{ ip saddr limit rate over {udp}/second burst {udp * 2} packets }} drop",
              f"udp dport {https_port} update @udp6 {{ ip6 saddr limit rate over {udp}/second burst {udp * 2} packets }} drop",
              f"icmp type echo-request limit rate over {icmp}/second burst {icmp * 2} packets drop",
              f"icmpv6 type echo-request limit rate over {icmp}/second burst {icmp * 2} packets drop"]
    out += ["    chain input {", "        type filter hook input priority filter - 10; policy accept;"]
    out += ["        " + r for r in rules] + ["    }", "}"]
    return "\n".join(out) + "\n"


# ----------------------------------------------------------------- origin guard (connect time)

ORIGIN_GUARD_TABLE = "pcdn_origin_guard"
# destinations a customer origin may never make the nginx workers connect to (is_public_ip == False)
ORIGIN_DENY4 = ("0.0.0.0/8", "10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12",
                "192.0.0.0/24", "192.0.2.0/24", "192.168.0.0/16", "198.18.0.0/15", "198.51.100.0/24",
                "203.0.113.0/24", "224.0.0.0/4", "240.0.0.0/4")
ORIGIN_DENY6 = ("::/127", "::ffff:0:0/96", "64:ff9b:1::/48", "100::/64", "2001::/23", "2001:db8::/32",
                "3fff::/20", "5f00::/16", "fc00::/7", "fe80::/10", "fec0::/10", "ff00::/8")


def _origin_deny6() -> list[str]:
    """ORIGIN_DENY6 plus the IPv6 forms that embed a denied IPv4 address (NAT64 64:ff9b::/96 and
    6to4 2002::/16), as netguard.is_public_ip judges them."""
    out = list(ORIGIN_DENY6)
    for n in ORIGIN_DENY4:
        v4 = ipaddress.ip_network(n)
        out.append(str(ipaddress.ip_network((int(ipaddress.ip_address("64:ff9b::")) | int(v4.network_address),
                                             96 + v4.prefixlen))))
        out.append(str(ipaddress.ip_network(((0x2002 << 112) | (int(v4.network_address) << 80), 16 + v4.prefixlen))))
    return out


def _resolver_endpoints(cfg: dict) -> tuple[list, list]:
    """RESOLVER as nftables (address, port) pairs (port 53 unless given): ([v4], [v6])."""
    v4, v6 = [], []
    for tok in str(cfg.get("RESOLVER") or "").split():
        m = re.match(r"^\[([0-9a-fA-F:.]+)\](?::(\d{1,5}))?$", tok) or re.match(r"^([0-9.]+)(?::(\d{1,5}))?$", tok) \
            or re.match(r"^([0-9a-fA-F:]+)()$", tok)
        if not m:
            continue
        try:
            ip = ipaddress.ip_address(m.group(1))
        except ValueError:
            continue
        port = int(m.group(2)) if m.group(2) and 0 < int(m.group(2)) < 65536 else 53
        (v4 if ip.version == 4 else v6).append((ip.compressed, port))
    return sorted(set(v4)), sorted(set(v6))


def nginx_uid(cfg: dict) -> int | None:
    import pwd
    try:
        return pwd.getpwnam(str(cfg.get("NGINX_USER") or "www-data")).pw_uid
    except (KeyError, TypeError):
        return None


def render_origin_guard(cfg: dict, uid: int | None = None) -> str:
    """nftables ruleset for the connect-time origin guard (install.sh, default on), table inet
    pcdn_origin_guard, loaded atomically like pcdn_guard. Only sockets of the nginx worker user
    (meta skuid) are judged, and of those only the first packet of an OUTGOING connection: a TCP
    SYN without ACK (connect()), or a new UDP flow from a non-listening port. The agent, pcdn-fn,
    pcdn-imaged, package updates and everything else run as other users and are never touched.
    Accepted first: DNS to RESOLVER, the edge's loopback services reached from INTERNAL_SRC,
    ORIGIN_PRIVATE_ALLOW and the shield peers (set peers4/peers6, kept in sync by the agent);
    then connections to loopback / private / link-local / CGNAT / ULA / multicast / reserved
    addresses or to any address of this host are rejected (TCP reset / ICMP: nginx answers 502)."""
    uid = nginx_uid(cfg) if uid is None else uid
    if uid is None or uid == 0:
        raise ValueError("origin guard: NGINX_USER must be an existing non-root user")
    r4, r6 = _resolver_endpoints(cfg)
    a4, a6 = [], []
    for n in origin_private_allow(cfg):
        (a4 if n.version == 4 else a6).append(str(n))
    ports = ", ".join(str(p) for p in internal_ports(cfg))
    https_port = _int(cfg.get("HTTPS_PORT"), 443, 1, 65535)
    shield_port = _int(cfg.get("SHIELD_HTTPS_PORT") or cfg.get("HTTPS_PORT"), 443, 1, 65535)
    lo, hi = l4_port_range(cfg)

    def iset(name, typ, elems):
        body = f"    set {name} {{\n        type {typ}\n        flags interval\n        auto-merge\n"
        if elems:
            body += "        elements = { " + ", ".join(elems) + " }\n"
        return body + "    }"

    out = ["# pcdn origin guard — generated by `pcdn-agent origin-guard`, do not edit.",
           "# The nginx workers may not connect to internal addresses on a customer's behalf (origin",
           "# host names resolving to loopback / private / metadata addresses). Allow private origins with",
           "# ORIGIN_PRIVATE_ALLOW in /etc/pcdn/agent.conf, then re-run install.sh --upgrade.",
           f"# Remove with: install.sh --upgrade --no-origin-guard (or: nft delete table inet {ORIGIN_GUARD_TABLE})",
           f"table inet {ORIGIN_GUARD_TABLE} {{}}", f"delete table inet {ORIGIN_GUARD_TABLE}",
           f"table inet {ORIGIN_GUARD_TABLE} {{",
           iset("deny4", "ipv4_addr", list(ORIGIN_DENY4)), iset("deny6", "ipv6_addr", _origin_deny6()),
           iset("allow4", "ipv4_addr", a4), iset("allow6", "ipv6_addr", a6),
           "    set peers4 {\n        type ipv4_addr\n    }", "    set peers6 {\n        type ipv6_addr\n    }",
           "    chain output {", "        type filter hook output priority filter; policy accept;",
           f"        meta skuid != {uid} accept",
           # only connect(): replies to visitors (also visitors on private networks) pass
           "        meta l4proto tcp tcp flags & (syn | ack) != syn accept",
           # replies of the QUIC listener / L4 UDP apps (their own listening ports)
           f"        meta l4proto udp udp sport {{ {(str(https_port) + ', ') if not lo <= https_port <= hi else ''}{lo}-{hi} }} accept",
           "        meta l4proto udp ct state != new accept",
           "        meta l4proto != { tcp, udp } accept"]
    for ip, port in r4:
        out.append(f"        ip daddr {ip} meta l4proto {{ tcp, udp }} th dport {port} accept")
    for ip, port in r6:
        out.append(f"        ip6 daddr {ip} meta l4proto {{ tcp, udp }} th dport {port} accept")
    out += [f"        ip saddr {internal_src(cfg)} ip daddr 127.0.0.1 tcp dport {{ {ports} }} accept",
            "        ip daddr @allow4 accept", "        ip6 daddr @allow6 accept",
            f"        ip daddr @peers4 tcp dport {shield_port} accept",
            f"        ip6 daddr @peers6 tcp dport {shield_port} accept"]
    for match in ("ip daddr @deny4", "ip6 daddr @deny6", "fib daddr type local"):
        out += [f"        meta l4proto tcp {match} counter reject with tcp reset",
                f"        {match} counter reject"]
    out += ["    }", "}"]
    return "\n".join(out) + "\n"
