"""Origin shield (SPEC §14.1): the node-wide shield block and its shield.conf."""

import re

from ..common import _int
from ..validation.origin import _ip_literal


# ----------------------------------------------------------------- origin shield (SPEC §14.1)

SAFE_SHIELD_SECRET = re.compile(r"^[0-9a-fA-F]{16,256}$")
SHIELD_MAX_PEERS = 64


def norm_shield(config: dict) -> dict | None:
    """Node-wide `shield` section {self, peers, secret}; None when unusable (no valid secret, or
    neither a shield itself nor any peer to send misses to). Missing -> today's behaviour."""
    sh = config.get("shield") if isinstance(config, dict) else None
    if not isinstance(sh, dict):
        return None
    secret = str(sh.get("secret") or "")
    if not SAFE_SHIELD_SECRET.match(secret):
        return None
    is_self = sh.get("self") is True
    peers = sorted({p for p in (_ip_literal(x) for x in (sh.get("peers") or []) if isinstance(x, str)) if p})
    peers = peers[:SHIELD_MAX_PEERS]
    if not is_self and not peers:
        return None
    # a shield never re-shields: its own misses always go to the origin
    return {"self": is_self, "peers": [] if is_self else peers, "secret": secret.lower()}


def render_shield(shield: dict | None, cfg: dict) -> str | None:
    """shield.conf (0600: it holds the shared secret). Shield nodes get the maps that accept a valid
    X-Pcdn-Shield hop; other nodes get the peer upstream (consistent hash on the request's cache key,
    $pcdn_ck) plus the header value they send. None when the node takes no part in shielding.
    The secret is fleet-wide and a valid hop skips the verdict / rate limits, so it only ever travels
    over TLS: edges shield only sites with a certificate (verified TLS hop) and a shield accepts the
    header only on a TLS connection ($https = on); over plain HTTP it is an ordinary visitor."""
    if not shield:
        return None
    sec = shield["secret"]
    out = ["# origin shield (SPEC §14.1) — generated by pcdn-agent, do not edit"]
    if shield["self"]:
        out += [
            "# a valid X-Pcdn-Shield received over TLS marks a cache miss forwarded by another edge;",
            "# anything else (no / wrong header, or any header over plain HTTP) is an ordinary visitor",
            f"map \"$https:$http_x_pcdn_shield\" $pcdn_shield_ok {{\n    default 0;\n    \"on:{sec}\" 1;\n}}",
            "# shield hops skip the security verdict (the visitor-facing edge already ran it) ...",
            "map $pcdn_shield_ok $pcdn_gate {\n    1       ok;\n    default $pcdn_verdict;\n}",
            "# ... keep the visitor's address / country / scheme the edge forwarded ...",
            "map $pcdn_shield_ok $pcdn_client_ip {\n    1       $http_x_real_ip;\n    default $remote_addr;\n}",
            "map $pcdn_shield_ok $pcdn_xff {\n    1       $http_x_forwarded_for;\n"
            "    default $proxy_add_x_forwarded_for;\n}",
            "map $pcdn_shield_ok $pcdn_cc {\n    1       $http_x_country_code;\n    default $pcdn_country;\n}",
            "map \"$pcdn_shield_ok:$http_x_forwarded_proto\" $pcdn_scheme {\n    \"1:https\" https;\n"
            "    \"1:http\"  http;\n    default   $scheme;\n}",
            "# ... and are not logged (usage is billed once, at the visitor-facing edge)",
            "map $pcdn_shield_ok $pcdn_log_ok {\n    1       0;\n    default 1;\n}",
        ]
        return "\n".join(out) + "\n"
    sp = _int(cfg.get("SHIELD_HTTPS_PORT") or cfg.get("HTTPS_PORT"), 443, 1, 65535)
    out += [
        "map $uri $pcdn_shield_ok {\n    default 0;\n}",
        "# cache key of the current request (set by each shielded location): every edge sends a given",
        "# object to the same shield, so it is fetched from the origin once",
        "map $uri $pcdn_ck {\n    default \"\";\n}",
        "# only GET/HEAD are shielded; other methods go straight to the origin (never replayed)",
        "map $request_method $pcdn_sh_skip {\n    GET     \"\";\n    HEAD    \"\";\n    default 1;\n}",
        f"geo $pcdn_shield_secret {{\n    default \"{sec}\";\n}}",
    ]
    servers = "".join(f"    server {p}:{sp} max_fails=1 fail_timeout=10s;\n" for p in shield["peers"])
    out.append(f"upstream pcdn_shield_https {{\n    hash $pcdn_ck consistent;\n{servers}"
               f"    keepalive 32;\n    keepalive_timeout 60s;\n}}")
    return "\n".join(out) + "\n"
