"""The whole rendered tree: every file under NGINX_DIR for one edge config (render_all) and the
tree digest substituted into /__pcdn/confver (render_tree)."""

import json

from ..common import _int
from ..reload import CONFVER_MARKER, tree_digest
from ..settings import asset
from ..validation.rules import norm_bot_ranges, norm_origin_pull
from ..capabilities import has_module
from .http import TICKET_FILES, norm_node, norm_tickets, render_bots, render_gates, render_http, render_mtls_resizer
from .probe import render_probe
from .shield import norm_shield, render_shield
from .site import _render_site, render_edge_auth
from .stream import render_l4


def render_all(config: dict, cfg: dict) -> dict:
    with open(asset(cfg, "NJS_FILE", "njs/pcdn.js")) as f:
        files = {"js/pcdn.js": f.read()}
    js_sites = {}
    max_timeout = 1
    shield = norm_shield(config)   # node-wide (SPEC §14.1); None -> today's behaviour
    sh_conf = render_shield(shield, cfg)
    if sh_conf:
        files["shield.conf"] = sh_conf
    platform = norm_origin_pull(config)   # node-wide platform client certificate (SPEC §14.2)
    platform_pair = (platform["cert"], platform["key"]) if platform else None
    resizer_pairs, platform_used, fn_any, sto_fetch = {}, False, False, False
    node = norm_node(config, cfg)
    for site in config.get("sites", []):
        text, extra, js, meta = _render_site(site, cfg, shield, platform_pair, node)
        fn_any = fn_any or bool(meta.get("functions"))
        sto_fetch = sto_fetch or bool(meta.get("storage_fetch"))
        files[f"sites/{int(site['id'])}.conf"] = text
        files.update(extra)
        platform_used = platform_used or meta.get("mtls_platform")
        if meta.get("mtls_resizer"):
            ident, pair = meta["mtls_resizer"]
            resizer_pairs[ident] = pair
        if js:
            js_sites[str(int(site["id"]))] = js
            for p in js["pools"].values():
                if p["health"]["enabled"] and p["health"].get("type") != "tcp":   # tcp: agent-checked
                    max_timeout = max(max_timeout, p["health"]["timeout"])
    sto_port = (_int(cfg.get("STORAGE_FETCH_PORT"), 8091, 1, 65535),) if sto_fetch else ()
    files.update(render_l4(config, cfg, sto_port))   # SPEC §16.4 ({} without L4 apps)
    if platform_used:   # one 0600 pair per node, only while some site presents it
        files["mtls/platform.crt"], files["mtls/platform.key"] = platform_pair
    # verified crawler ranges: only while some site uses bot management (a daily range refresh
    # must not reload nodes where nobody needs them)
    # (also for a waiting room that lets verified crawlers through, SPEC §18.1)
    bots_conf = render_bots(norm_bot_ranges(config)) if any(
        "bots" in j or ((j.get("waiting_room") or {}).get("bypass") or {}).get("bots")
        for j in js_sites.values()) else None
    if bots_conf:
        files["bots.conf"] = bots_conf
    mtls_conf = render_mtls_resizer(resizer_pairs)
    if mtls_conf:
        files["mtls.conf"] = mtls_conf
    # SPEC §22.8 shared session-ticket keys (raw 80-byte files, 0600; a GLOBAL change: one reload each)
    tickets = norm_tickets(config) or []
    for rel, key in zip(TICKET_FILES, tickets):
        files[rel] = key
    files["http.conf"] = render_http(cfg, max_timeout + 1, shield, bool(bots_conf), bool(mtls_conf),
                                     node, render_probe(cfg), len(tickets))
    if fn_any:   # SPEC §16.9: the fetch() socket answers 421 for any host without a fetch server
        files["http.conf"] += ("\n# edge functions fetch() socket (SPEC §16.9): unknown hosts\nserver {\n"
                               f"    listen unix:{cfg.get('FN_FETCH_SOCKET') or '/run/pcdn-fnfetch/fetch.sock'} "
                               "default_server;\n    server_name _;\n    access_log off;\n    return 421;\n}\n")
    if sto_fetch:   # SPEC §16.8: the resizer's storage-origin port answers 404 for any other host
        files["http.conf"] += ("\n# object-storage origins for the image resizer (SPEC §16.8): unknown hosts\nserver {\n"
                               f"    listen 127.0.0.1:{_int(cfg.get('STORAGE_FETCH_PORT'), 8091, 1, 65535)} "
                               "default_server;\n    server_name _;\n    access_log off;\n    return 404;\n}\n")
    # SPEC §18.1 / §18.2 visitor gates: http-level dict / variables, the controller token for the OTP
    # hop (0600, nginx master only); only while some site uses them and the node has njs
    wr_any = any("waiting_room" in j for j in js_sites.values())
    acc_any = any("access" in j for j in js_sites.values())
    if (wr_any or acc_any) and has_module(cfg, "njs"):
        files["http.conf"] += render_gates(cfg, wr_any, acc_any)
        if acc_any:
            files["edge-auth.conf"] = render_edge_auth(cfg)
    # JSON is valid JS; ensure_ascii keeps U+2028 & co. out of the source
    files["js/sites.js"] = ("// generated by pcdn-agent, do not edit\nexport default "
                            + json.dumps(js_sites, ensure_ascii=True, sort_keys=True) + ";\n")
    return files


def render_tree(config: dict, cfg: dict) -> tuple[dict, str]:
    """Rendered files plus the tree digest. The digest is computed over the tree while http.conf
    still carries the CONFVER_MARKER placeholder (F29: the digest must not depend on itself), then
    substituted into the /__pcdn/confver endpoint so the agent can verify the reload took effect."""
    files = render_all(config, cfg)
    digest = tree_digest(files)
    if "http.conf" in files:
        files["http.conf"] = files["http.conf"].replace(CONFVER_MARKER, digest)
    return files, digest
