// Pasargad CDN — edge request logic for nginx njs (>= 0.8.1).
//
// Imported by the http.conf rendered by pcdn-agent. Per-site data comes from
// sites.js (generated by the agent next to this file, compiled once at config
// load), so nothing here parses configuration per request.
//
// Exports:
//   verdict  js_set $pcdn_verdict  — "ok" | "<action>:<source>:<rule>"
//   upstream js_set $pcdn_upstream — "host:port" chosen from a load-balancer pool
//   tunnelUpstream js_set $pcdn_tn_upstream — same for the pool of a tunnel path ($pcdn_tn_pool)
//   imgW/imgH/imgQ js_set          — image resize parameters ("" = no resize)
//   deny / verify / captcha        — js_content handlers for /__pcdn/*
//   health                         — js_periodic origin health checker
//
// njs 0.8.2 notes: no destructuring/spread/classes/optional chaining/BigInt,
// shared-dict entries only expire through the zone-wide timeout.

import SITES from 'sites.js';
import cr from 'crypto';

const CLR_COOKIE = '__pcdn_clr';
const POW_DIFFICULTY = 4;          // leading hex zeros of sha256(nonce:n)  (~65k hashes)
const TOKEN_TTL = 300;             // challenge / captcha token lifetime (s)
const HC_FALL = 2;                 // consecutive failures before an origin is "down"
const CAPTCHA_ALPHABET = 'ACEFHKLMNPRTUVWXYZ347';
const CAPTCHA_LEN = 5;

// ------------------------------------------------------------------ helpers

function now() { return Math.floor(Date.now() / 1000); }
function hmac(key, s) { return cr.createHmac('sha256', key).update(s).digest('hex'); }
function sha256(s) { return cr.createHash('sha256').update(s).digest('hex'); }

function safeEq(a, b) {
    if (typeof a !== 'string' || typeof b !== 'string' || a.length !== b.length) return false;
    let x = 0;
    for (let i = 0; i < a.length; i++) x |= a.charCodeAt(i) ^ b.charCodeAt(i);
    return x === 0;
}

function randHex(n) {
    const b = crypto.getRandomValues(new Uint8Array(n));
    let s = '';
    for (let i = 0; i < b.length; i++) s += (b[i] < 16 ? '0' : '') + b[i].toString(16);
    return s;
}

function pctDecode(s) {
    try { return decodeURIComponent(s); } catch (e) {
        // malformed / non-UTF-8 escapes: decode byte-wise so signatures still see them
        return s.replace(/%([0-9a-fA-F]{2})/g, function (m, h) { return String.fromCharCode(parseInt(h, 16)); });
    }
}

function clean(s) { return String(s || '').toLowerCase().replace(/[^a-z0-9_-]/g, '').substring(0, 32) || 'x'; }

function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function reOrNull(src, flags) {
    if (src === null || src === undefined || src === '') return null;
    try { return new RegExp(src, flags); } catch (e) { return null; }
}

// ------------------------------------------------------------------ IP / CIDR

function ip4(s) {
    const p = s.split('.');
    if (p.length !== 4) return null;
    let n = 0;
    for (let i = 0; i < 4; i++) {
        if (!/^\d{1,3}$/.test(p[i]) || +p[i] > 255) return null;
        n = n * 256 + +p[i];
    }
    return n;
}

function ip6(s) {
    s = s.toLowerCase();
    let tail = [];
    const m = s.match(/^(.*:)(\d+\.\d+\.\d+\.\d+)$/);   // ::ffff:1.2.3.4
    if (m) {
        const v4 = ip4(m[2]);
        if (v4 === null) return null;
        tail = [Math.floor(v4 / 65536), v4 % 65536];
        s = m[1].endsWith('::') ? m[1] : m[1].slice(0, -1);
    }
    const halves = s.split('::');
    if (halves.length > 2) return null;
    const part = function (x) { return x === '' ? [] : x.split(':'); };
    const head = part(halves[0]), rest = halves.length === 2 ? part(halves[1]) : [];
    const groups = head.concat(rest);
    for (let i = 0; i < groups.length; i++) if (!/^[0-9a-f]{1,4}$/.test(groups[i])) return null;
    const want = 8 - tail.length;
    if (halves.length === 1 && groups.length !== want) return null;
    if (groups.length > want) return null;
    const out = [];
    for (let i = 0; i < head.length; i++) out.push(parseInt(head[i], 16));
    for (let i = 0; i < want - groups.length; i++) out.push(0);
    for (let i = 0; i < rest.length; i++) out.push(parseInt(rest[i], 16));
    return out.concat(tail);
}

function parseIP(s) {
    s = String(s || '');
    if (s.indexOf(':') >= 0) { const a = ip6(s); return a ? { v: 6, a: a } : null; }
    const n = ip4(s);
    return n === null ? null : { v: 4, n: n };
}

function cidr(s) {
    s = String(s || '').trim();
    const i = s.indexOf('/');
    const ip = parseIP(i < 0 ? s : s.substring(0, i));
    if (!ip) return null;
    const max = ip.v === 4 ? 32 : 128;
    const bits = i < 0 ? max : parseInt(s.substring(i + 1), 10);
    if (!(bits >= 0 && bits <= max)) return null;
    ip.bits = bits;
    return ip;
}

function inCidr(ip, c) {
    if (!ip || ip.v !== c.v) return false;
    if (c.v === 4) {
        const d = Math.pow(2, 32 - c.bits);
        return Math.floor(ip.n / d) === Math.floor(c.n / d);
    }
    for (let i = 0; i < 8; i++) {
        const b = Math.min(16, Math.max(0, c.bits - 16 * i));
        if (b === 0) return true;
        if ((ip.a[i] >> (16 - b)) !== (c.a[i] >> (16 - b))) return false;
    }
    return true;
}

// ------------------------------------------------------------------ WAF signatures
// t = targets: p path, q query args (names+values), c cookie values, u user agent, r referer.
// Ids follow the OWASP CRS numbering scheme so they read familiar in the panel.

const WAF_RULES = [
    // SQL injection
    { id: 942100, g: 'sqli', pl: 1, t: 'qc', re: /['"`)]\s*(?:or|and|xor|\|\||&&)\s*['"`(]?\s*[\w-]*\s*['"`]?\s*(?:=|<>|!=|<|>|\blike\b|\bis\b|\bin\s*\()/ },
    { id: 942110, g: 'sqli', pl: 1, t: 'qc', re: /\b(?:or|and)\s+['"]?\d+['"]?\s*(?:=|<|>)\s*['"]?\d+/ },
    { id: 942190, g: 'sqli', pl: 1, t: 'qc', re: /\bunion\b(?:\s+(?:all|distinct))?\s*(?:\(\s*)?select\b/ },
    { id: 942160, g: 'sqli', pl: 1, t: 'qc', re: /\b(?:sleep|benchmark|pg_sleep|extractvalue|updatexml)\s*\(|\bwaitfor\s+delay\b/ },
    { id: 942140, g: 'sqli', pl: 1, t: 'qc', re: /\binformation_schema\b|\bmysql\.user\b|\bsys\.(?:objects|databases|tables)\b|\bpg_catalog\b|\bsqlite_master\b/ },
    { id: 942200, g: 'sqli', pl: 2, t: 'qc', re: /;\s*(?:drop|delete|insert|update|alter|create|truncate|exec)\s+/ },
    { id: 942300, g: 'sqli', pl: 2, t: 'qc', re: /['"`]\s*(?:--|#)|\/\*!\d*/ },
    { id: 942400, g: 'sqli', pl: 2, t: 'qc', re: /\b(?:select\b.{1,200}\bfrom|insert\s+into|delete\s+from|update\b.{1,100}\bset)\b/ },
    { id: 942430, g: 'sqli', pl: 3, t: 'q', re: /(?:[~!@#$%^&*()\-+={}[\]|:;"'`<>][^~!@#$%^&*()\-+={}[\]|:;"'`<>]*){12}/ },
    // XSS
    { id: 941100, g: 'xss', pl: 1, t: 'qcpr', re: /<script[\s>\/]|<\/script\s*>/ },
    { id: 941110, g: 'xss', pl: 1, t: 'qcr', re: /\bon(?:error|load|click|dblclick|mouse\w+|focus\w*|blur|submit|change|key\w+|animation\w+|transition\w+|toggle|pointer\w+|begin|input|wheel)\s*=/ },
    { id: 941120, g: 'xss', pl: 1, t: 'qcr', re: /\b(?:java|vb)script\s*:/ },
    { id: 941130, g: 'xss', pl: 1, t: 'qcp', re: /<(?:iframe|object|embed|svg|math|base|link|meta|form|frameset|applet)\b/ },
    { id: 941140, g: 'xss', pl: 2, t: 'qc', re: /<img\b[^>]*\bsrc\s*=|\bsrcdoc\s*=|data:text\/html/ },
    { id: 941150, g: 'xss', pl: 2, t: 'qc', re: /\bdocument\.(?:cookie|domain|write|location)|\bwindow\.location|\b(?:eval|alert|prompt|confirm)\s*\(|fromcharcode/ },
    { id: 941160, g: 'xss', pl: 3, t: 'qc', re: /<[a-z!\/?]/ },
    // Local file inclusion / traversal
    { id: 930100, g: 'lfi', pl: 1, t: 'pq', re: /(?:^|[\/\\=])\.\.(?:[\/\\]|$)/ },
    { id: 930110, g: 'lfi', pl: 1, t: 'pq', re: /(?:^|[\/\\])(?:etc[\/\\](?:passwd|shadow|group|hosts|issue)|proc[\/\\]self[\/\\]|windows[\/\\](?:win\.ini|system32))|boot\.ini/ },
    { id: 930120, g: 'lfi', pl: 2, t: 'pq', re: /\.(?:htaccess|htpasswd|bash_history|ssh[\/\\])|[\/\\]\.aws[\/\\]/ },
    // Remote command execution
    { id: 932100, g: 'rce', pl: 1, t: 'q', re: /(?:[;|&`\n]|\$\()\s*(?:cat|ls|id|whoami|uname|wget|curl|nc|ncat|bash|sh|zsh|python\d?|perl|ruby|chmod|rm|ping|nslookup|powershell|cmd)\b/ },
    { id: 932110, g: 'rce', pl: 1, t: 'qucr', re: /\$\{(?:jndi|env|sys|lower|upper|date|java|::-)/ },
    { id: 932120, g: 'rce', pl: 1, t: 'q', re: /\/bin\/(?:ba|z|da)?sh\b|\bcmd(?:\.exe)?\s+\/c\b|\bpowershell(?:\.exe)?\s+-/ },
    { id: 932140, g: 'rce', pl: 1, t: 'qucr', re: /\(\)\s*\{\s*:\s*;\s*\}/ },
    { id: 932130, g: 'rce', pl: 2, t: 'q', re: /`[^`]{1,100}`|\$\([^)]{1,100}\)/ },
    // PHP injection
    { id: 933100, g: 'php', pl: 1, t: 'qc', re: /<\?(?:php|=)/ },
    { id: 933110, g: 'php', pl: 1, t: 'qc', re: /\b(?:php|phar|expect):\/\// },
    { id: 933130, g: 'php', pl: 1, t: 'qc', re: /\b(?:base64_decode|system|passthru|shell_exec|proc_open|popen|pcntl_exec|assert|create_function|call_user_func(?:_array)?|gzinflate|str_rot13)\s*\(/ },
    { id: 933120, g: 'php', pl: 2, t: 'qc', re: /\b(?:data|glob|zip|zlib|compress\.zlib|ogg|rar|ssh2):\/\// },
    { id: 933140, g: 'php', pl: 2, t: 'qc', re: /\$_(?:get|post|cookie|request|server|files|env|session)\b|\$globals\b/ },
    // Scanners
    { id: 913100, g: 'scanner', pl: 1, t: 'u', re: /sqlmap|nikto|nmap|masscan|acunetix|nessus|wpscan|dirbuster|gobuster|havij|w3af|zgrab|nuclei|openvas|arachni|netsparker|jaeles|ffuf|fimap|whatweb|feroxbuster/ },
    { id: 913120, g: 'scanner', pl: 1, t: 'p', re: /\/\.(?:git|svn|hg|env)(?:\/|$)/ },
    { id: 913130, g: 'scanner', pl: 2, t: 'p', re: /\.(?:sql|bak|old|swp|orig)$|\/wp-config\.php./ },
    { id: 913110, g: 'scanner', pl: 3, t: 'u', re: /python-requests|go-http-client|libwww-perl|^curl\/|^wget\// },
];

const ALLOWED_METHODS = { GET: 1, HEAD: 1, POST: 1, PUT: 1, PATCH: 1, DELETE: 1, OPTIONS: 1 };
const RESTRICTED_EXT = /\.(?:asa|asax|backup|bat|cdx|cer|cfg|cmd|com|config|conf|cs|csproj|csr|dat|db|dbf|dll|dos|htr|htw|ida|idc|idq|inc|ini|key|licx|lnk|log|mdb|pass|pdb|pol|printer|pwd|rdb|resources|resx|sys|vb|vbs|vbproj|vsdisco|webinfo|xsd|xsx)$/;

// protocol checks: function(ctx) -> true when the request violates it
const WAF_PROTOCOL = [
    { id: 920100, pl: 1, f: function (c) { return !ALLOWED_METHODS[c.method]; } },
    { id: 920270, pl: 1, f: function (c) { return /%(?:0[0-8bcef]|1[0-9a-f]|7f)/i.test(c.rawUri); } },
    { id: 920220, pl: 1, f: function (c) { return /%(?![0-9a-fA-F]{2})/.test(c.rawUri); } },
    { id: 920170, pl: 2, f: function (c) { return (c.method === 'GET' || c.method === 'HEAD') && +(c.r.headersIn['Content-Length'] || 0) > 0; } },
    { id: 920230, pl: 2, f: function (c) { return /%25[0-9a-fA-F]{2}/.test(c.rawUri); } },
    { id: 920300, pl: 2, f: function (c) { return !c.ua; } },
    { id: 920440, pl: 2, f: function (c) { return RESTRICTED_EXT.test(c.pathL); } },
];

// ------------------------------------------------------------------ site preparation (once per config load)

function wildHost(p) {
    p = String(p).toLowerCase();
    if (p.indexOf('*.') === 0) { const suf = p.substring(1); return function (h) { return h.endsWith(suf); }; }
    return function (h) { return h === p; };
}

const STRING_OPS = {
    eq: function (v, x) { return v === x; },
    contains: function (v, x) { return v.indexOf(x) >= 0; },
    starts_with: function (v, x) { return v.indexOf(x) === 0; },
    ends_with: function (v, x) { return x.length <= v.length && v.substring(v.length - x.length) === x; },
    in: function (v, x) { return v === x; },
};
const NEGATED = { ne: 'eq', not_contains: 'contains', not_in: 'in' };

function compileCond(c) {
    const field = c.field, name = c.name ? String(c.name) : '';
    let op = c.op, neg = false;
    if (NEGATED[op]) { neg = true; op = NEGATED[op]; }
    const vals = (Array.isArray(c.value) ? c.value : [c.value]).map(function (v) { return String(v === null ? '' : v); });
    let test;
    if (field === 'ip') {
        const nets = vals.map(cidr).filter(Boolean);
        test = function (ctx) { return nets.some(function (n) { return inCidr(ctx.ip, n); }); };
    } else if (field === 'country') {
        // unknown country (no GeoIP database / unlisted IP) matches neither `in` nor `not_in`,
        // so "block everything not_in [IR]" cannot lock out every visitor
        const cc = vals.map(function (v) { return v.toUpperCase(); });
        return function (ctx) { return !!ctx.country && (cc.indexOf(ctx.country) >= 0) !== neg; };
    } else {
        let one;
        if (op === 'regex') {
            const res = vals.map(function (v) { return reOrNull(v, 'i'); }).filter(Boolean);
            one = function (v) { return res.some(function (re) { return re.test(v); }); };
        } else if (STRING_OPS[op]) {
            const fn = STRING_OPS[op], lv = vals.map(function (v) { return v.toLowerCase(); });
            one = function (v) { v = v.toLowerCase(); return lv.some(function (x) { return fn(v, x); }); };
        } else {
            one = function () { return false; };
        }
        test = function (ctx) { return one(fieldValue(ctx, field, name)); };
    }
    return neg ? function (ctx) { return !test(ctx); } : test;
}

function fieldValue(ctx, field, name) {
    switch (field) {
    case 'path': return ctx.path;
    case 'host': return ctx.host;
    case 'query': return ctx.query();
    case 'user_agent': return ctx.ua;
    case 'referer': return ctx.referer;
    case 'method': return ctx.method;
    case 'header': return String(ctx.r.headersIn[name] || '');
    }
    return '';
}

function prepSite(id, s) {
    const P = { id: id, domain: s.domain, secret: String(s.secret || ''), hosts: (s.hosts || []).map(wildHost) };
    P.blocked = (s.blocked_ips || []).map(cidr).filter(Boolean);
    // tunnel path prefixes (nginx "location ^~" on the same normalised $uri)
    P.tunnel = (s.tunnel_paths || []).map(String).filter(function (p) { return p.charAt(0) === '/' && p.length > 1; });
    P.minTls13 = s.min_tls === '1.3';

    const fw = s.firewall || {};
    P.fwDefault = fw.default_action === 'block' ? 'block' : 'allow';
    P.fwRules = (fw.rules || []).filter(function (r) { return r.enabled !== false; }).map(function (r) {
        return { id: clean(r.id), action: r.action, conds: (r.conditions || []).map(compileCond) };
    });

    const hl = s.hotlink || {};
    P.hotlink = hl.enabled ? {
        ext: reOrNull('\\.(?:' + (hl.extensions || []).map(function (e) { return String(e).replace(/[^a-z0-9]/gi, ''); })
            .filter(Boolean).join('|') + ')$', 'i'),
        allowed: (hl.allowed_referers || []).map(wildHost),
        allowEmpty: hl.allow_empty !== false,
    } : null;

    P.rl = (s.ratelimit || []).map(function (r) {
        return { id: clean(r.id), re: reOrNull(r.path_re, ''), methods: r.methods || [], requests: +r.requests || 1,
            period: Math.max(1, +r.period || 60), action: r.action || 'block', blockSeconds: Math.max(1, +r.block_seconds || 60) };
    });

    const dd = s.ddos || {};
    P.ddos = { mode: dd.mode || 'off', threshold: Math.max(1, +dd.threshold_rps || 200), ttl: Math.max(60, +dd.clearance_ttl || 3600) };

    const w = s.waf || {};
    const groups = {};
    (w.groups || []).forEach(function (g) { groups[g] = 1; });
    const pl = Math.min(3, Math.max(1, +w.paranoia || 1));
    P.waf = {
        mode: w.mode || 'off',
        rules: WAF_RULES.filter(function (r) { return groups[r.g] && r.pl <= pl; }),
        proto: groups.protocol ? WAF_PROTOCOL.filter(function (r) { return r.pl <= pl; }) : [],
        excl: (w.exclusions || []).map(function (e) { return { id: +e.rule_id || 0, re: reOrNull(e.path_re, '') }; }),
        off: (w.off_paths || []).map(function (p) { return reOrNull(p, ''); }).filter(Boolean),
    };

    P.pools = {};
    Object.keys(s.pools || {}).forEach(function (name) {
        const p = s.pools[name], h = p.health || {};
        P.pools[name] = {
            name: name, method: p.method === 'ip_hash' ? 'ip_hash' : 'weighted', protocol: p.protocol === 'https' ? 'https' : 'http',
            origins: (p.origins || []).map(function (o) { return { hp: o.hp, weight: Math.max(1, +o.weight || 1), backup: !!o.backup }; }),
            health: { enabled: !!h.enabled, path: h.path || '/', interval: Math.max(1, +h.interval || 10),
                timeout: Math.min(10, Math.max(1, +h.timeout || 3)), expect: String(h.expect || '2xx,3xx').toLowerCase().split(','),
                host: h.host || s.domain },
        };
    });

    const im = s.image || {};
    P.image = im.enabled ? { quality: Math.min(100, Math.max(1, +im.quality || 85)), max: Math.max(16, +im.max_width || 2000) } : null;
    return P;
}

const S = {};
Object.keys(SITES).forEach(function (id) {
    try { S[id] = prepSite(id, SITES[id]); } catch (e) { S[id] = null; }  // fail open for a broken site entry
});

function siteOf(r) { const id = r.variables.pcdn_site; return id ? S[id] || null : null; }

function inTunnel(site, uri) {
    for (let i = 0; i < site.tunnel.length; i++) if (String(uri).indexOf(site.tunnel[i]) === 0) return true;
    return false;
}

// ------------------------------------------------------------------ request context

function mkctx(r, site) {
    const ctx = {
        r: r, site: site,
        ipStr: r.variables.remote_addr, ip: parseIP(r.variables.remote_addr),
        country: String(r.variables.pcdn_country || '').toUpperCase(),
        host: String(r.variables.host || '').toLowerCase(),
        method: r.method,
        path: r.uri,
        pathL: String(r.uri).toLowerCase(),
        rawUri: String(r.variables.request_uri || ''),
        args: String(r.variables.args || ''),
        ua: String(r.headersIn['User-Agent'] || ''),
        referer: String(r.headersIn.Referer || ''),
        _q: null, _clr: -1,
    };
    ctx.query = function () { if (ctx._q === null) ctx._q = pctDecode(ctx.args.replace(/\+/g, ' ')); return ctx._q; };
    return ctx;
}

// clearance level carried by the cookie: 0 none, 1 JS challenge, 2 captcha
function clearance(ctx) {
    if (ctx._clr >= 0) return ctx._clr;
    ctx._clr = 0;
    const c = ctx.r.variables['cookie_' + CLR_COOKIE];
    if (c) {
        const p = String(c).split('.');
        if (p.length === 3 && +p[0] > now() && (p[1] === 'js' || p[1] === 'cap')
            && safeEq(p[2], clrSig(ctx.site, ctx.ipStr, ctx.ua, p[0], p[1]))) {
            ctx._clr = p[1] === 'cap' ? 2 : 1;
        }
    }
    return ctx._clr;
}

function clrSig(site, ip, ua, exp, level) { return hmac(site.secret, 'clr|' + ip + '|' + ua + '|' + exp + '|' + level); }

// challenge-type actions are satisfied by a valid clearance cookie
function challengeOr(ctx, action, source, rule) {
    const need = action === 'captcha' ? 2 : 1;
    return clearance(ctx) >= need ? null : action + ':' + source + ':' + rule;
}

// ------------------------------------------------------------------ verdict

function verdict(r) {
    const memo = r.variables.pcdn_vmemo;   // js_var: survives internal redirects, so counters run once
    if (memo) return memo;
    let v = 'ok';
    try { v = evaluate(r); } catch (e) { r.error('pcdn verdict: ' + e); v = 'ok'; }
    r.variables.pcdn_vmemo = v;
    return v;
}

function evaluate(r) {
    if (String(r.uri).indexOf('/__pcdn/') === 0) return 'ok';
    const site = siteOf(r);
    if (!site) return 'ok';
    const ctx = mkctx(r, site);
    let logged = null, v;

    if (site.minTls13 && r.variables.ssl_protocol && r.variables.ssl_protocol !== 'TLSv1.3') return 'block:firewall:min_tls';
    for (let i = 0; i < site.blocked.length; i++) if (inCidr(ctx.ip, site.blocked[i])) return 'block:firewall:blocked_ips';
    if (site.tunnel.length && inTunnel(site, ctx.path)) return tunnelVerdict(ctx, site);

    // firewall: first matching rule wins; allow short-circuits everything; log continues
    let matched = false;
    for (let i = 0; i < site.fwRules.length && !matched; i++) {
        const rule = site.fwRules[i];
        if (!rule.conds.every(function (c) { return c(ctx); })) continue;
        if (rule.action === 'log') { if (!logged) logged = 'log:firewall:' + rule.id; continue; }
        matched = true;
        if (rule.action === 'allow') return logged || 'ok';
        if (rule.action === 'block') return 'block:firewall:' + rule.id;
        if (rule.action === 'challenge' || rule.action === 'captcha') {
            v = challengeOr(ctx, rule.action, 'firewall', rule.id);
            if (v) return v;
        }
    }
    if (!matched && site.fwDefault === 'block') return 'block:firewall:default';

    if (site.hotlink && site.hotlink.ext && site.hotlink.ext.test(ctx.path) && !hotlinkOk(ctx, site)) return 'block:hotlink:referer';

    v = rateLimit(ctx, site);
    if (v) return v;
    v = ddos(ctx, site);
    if (v) return v;
    v = waf(ctx, site);
    if (v) {
        if (v.indexOf('log:') !== 0) return v;
        if (!logged) logged = v;
    }
    return logged || 'ok';
}

// Tunnel paths (VPN streams): firewall allow/block/log rules and the default action only.
// Challenge / captcha rules, hotlink, rate limits, DDoS and WAF are skipped: a VPN client
// cannot solve a challenge and binary stream payloads only produce WAF false positives.
function tunnelVerdict(ctx, site) {
    let logged = null;
    for (let i = 0; i < site.fwRules.length; i++) {
        const rule = site.fwRules[i];
        if (rule.action === 'challenge' || rule.action === 'captcha') continue;
        if (!rule.conds.every(function (c) { return c(ctx); })) continue;
        if (rule.action === 'log') { if (!logged) logged = 'log:firewall:' + rule.id; continue; }
        if (rule.action === 'allow') return logged || 'ok';
        return 'block:firewall:' + rule.id;
    }
    if (site.fwDefault === 'block') return 'block:firewall:default';
    return logged || 'ok';
}

function hotlinkOk(ctx, site) {
    if (!ctx.referer) return site.hotlink.allowEmpty;
    const m = ctx.referer.match(/^[a-z][a-z0-9+.-]*:\/\/(?:[^@/?#]*@)?([^/?#:]+)/i);
    if (!m) return false;
    const h = m[1].toLowerCase();
    const ok = function (f) { return f(h); };
    return h === ctx.host || site.hosts.some(ok) || site.hotlink.allowed.some(ok);
}

function rateLimit(ctx, site) {
    if (!site.rl.length) return null;
    const cnt = ngx.shared.pcdn_cnt, blk = ngx.shared.pcdn_blk, t = now();
    for (let i = 0; i < site.rl.length; i++) {
        const rule = site.rl[i];
        if (!rule.re || !rule.re.test(ctx.path)) continue;
        if (rule.methods.length && rule.methods.indexOf(ctx.method) < 0) continue;
        const bkey = 'b:' + site.id + ':' + rule.id + ':' + ctx.ipStr;
        if (rule.action === 'block' && (blk.get(bkey) || 0) > t) return 'block:ratelimit:' + rule.id;
        const n = cnt.incr('r:' + site.id + ':' + rule.id + ':' + ctx.ipStr + ':' + Math.floor(t / rule.period), 1, 0);
        if (n <= rule.requests) continue;
        if (rule.action === 'block') {
            blk.set(bkey, t + rule.blockSeconds);
            return 'block:ratelimit:' + rule.id;
        }
        const v = challengeOr(ctx, rule.action === 'captcha' ? 'captcha' : 'challenge', 'ratelimit', rule.id);
        if (v) return v;
    }
    return null;
}

function ddos(ctx, site) {
    const d = site.ddos;
    if (d.mode === 'js') return challengeOr(ctx, 'challenge', 'ddos', 'js');
    if (d.mode === 'captcha') return challengeOr(ctx, 'captcha', 'ddos', 'captcha');
    if (d.mode !== 'auto') return null;
    // per-site request count in 10 s windows (shared by all workers of this edge)
    const cnt = ngx.shared.pcdn_cnt, w = Math.floor(now() / 10), k = 'd:' + site.id + ':';
    const cur = cnt.incr(k + w, 1, 0), prev = cnt.get(k + (w - 1)) || 0;
    const limit = d.threshold * 10;
    if (cur > limit || prev > limit) return challengeOr(ctx, 'challenge', 'ddos', 'auto');
    return null;
}

function normalize(s) {
    s = String(s);
    if (s.length > 4096) s = s.substring(0, 4096);
    if (/%[0-9a-f]{2}/i.test(s)) s = pctDecode(s);            // double-encoded payloads
    return s.toLowerCase().replace(/\/\*.*?\*\//g, ' ').replace(/\s+/g, ' ');
}

function wafTargets(ctx) {
    const t = { p: [normalize(ctx.path)], q: [], c: [], u: [normalize(ctx.ua)], r: [] };
    if (ctx.args) {
        ctx.args.split('&').forEach(function (kv) {
            if (!kv) return;
            const i = kv.indexOf('=');
            const k = pctDecode((i < 0 ? kv : kv.substring(0, i)).replace(/\+/g, ' '));
            t.q.push(normalize(k));
            if (i >= 0) t.q.push(normalize(pctDecode(kv.substring(i + 1).replace(/\+/g, ' '))));
        });
    }
    const cookie = ctx.r.headersIn.Cookie;
    if (cookie) {
        String(cookie).split(';').forEach(function (kv) {
            const i = kv.indexOf('=');
            if (i >= 0) t.c.push(normalize(pctDecode(kv.substring(i + 1))));
        });
    }
    if (ctx.referer) t.r.push(normalize(ctx.referer));
    return t;
}

function wafExcluded(w, id, path) {
    return w.excl.some(function (e) { return (e.id === 0 || e.id === id) && (!e.re || e.re.test(path)); });
}

function waf(ctx, site) {
    const w = site.waf;
    if (w.mode !== 'block' && w.mode !== 'detect') return null;
    if (w.off.some(function (re) { return re.test(ctx.path); })) return null;
    let hit = 0;
    for (let i = 0; i < w.proto.length && !hit; i++) {
        const pr = w.proto[i];
        if (!wafExcluded(w, pr.id, ctx.path) && pr.f(ctx)) hit = pr.id;
    }
    if (!hit && w.rules.length) {
        const T = wafTargets(ctx);
        for (let i = 0; i < w.rules.length && !hit; i++) {
            const rule = w.rules[i];
            if (wafExcluded(w, rule.id, ctx.path)) continue;
            for (let j = 0; j < rule.t.length && !hit; j++) {
                const vals = T[rule.t.charAt(j)];
                for (let k = 0; k < vals.length; k++) if (rule.re.test(vals[k])) { hit = rule.id; break; }
            }
        }
    }
    if (!hit) return null;
    return (w.mode === 'block' ? 'block' : 'log') + ':waf:' + hit;
}

// ------------------------------------------------------------------ load balancing

function fnv(s) {
    let h = 0x811c9dc5;
    for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619) >>> 0; }
    return h;
}

function hcKey(site, pool, o) { return site.id + '|' + pool.name + '|' + o.hp; }

function isUp(site, pool, o) {
    if (!pool.health.enabled) return true;
    return (ngx.shared.pcdn_hc.get(hcKey(site, pool, o)) || 0) < HC_FALL;
}

function upstream(r) { return pick(r, r.variables.pcdn_pool); }
function tunnelUpstream(r) { return pick(r, r.variables.pcdn_tn_pool); }

function pick(r, poolName) {
    const site = siteOf(r), pool = site ? site.pools[poolName] : null;
    if (!pool || !pool.origins.length) return '127.0.0.1:9';   // discard port -> 502, never an open proxy
    let cand = pool.origins.filter(function (o) { return !o.backup && isUp(site, pool, o); });
    if (!cand.length) cand = pool.origins.filter(function (o) { return o.backup && isUp(site, pool, o); });
    if (!cand.length) cand = pool.origins.filter(function (o) { return !o.backup; });   // fail open
    if (!cand.length) cand = pool.origins;
    let total = 0;
    cand.forEach(function (o) { total += o.weight; });
    let x = pool.method === 'ip_hash' ? fnv(String(r.variables.remote_addr)) % total : Math.random() * total;
    for (let i = 0; i < cand.length; i++) {
        x -= cand[i].weight;
        if (x < 0) return cand[i].hp;
    }
    return cand[cand.length - 1].hp;
}

function expectOk(expect, status) {
    const s = String(status);
    return expect.some(function (e) {
        e = e.trim();
        return e.length === 3 && (e === s || (e.substring(1) === 'xx' && e.charAt(0) === s.charAt(0)));
    });
}

async function checkOrigin(site, pool, o) {
    const hc = ngx.shared.pcdn_hc, key = hcKey(site, pool, o);
    // Pessimistic: count the failure up front. njs kills a periodic instance that is still
    // running at the next tick, so a hung check must already be recorded as failed.
    hc.incr(key, 1, 0);
    let timer, ok = false;
    const timeout = new Promise(function (res, rej) {
        timer = setTimeout(function () { rej(new Error('timeout')); }, pool.health.timeout * 1000);
    });
    try {
        const res = await Promise.race([
            ngx.fetch(pool.protocol + '://' + o.hp + pool.health.path, {
                headers: { Host: pool.health.host, 'User-Agent': 'pcdn-health/2' },
                verify: false, max_response_body_size: 65536 }),
            timeout,
        ]);
        ok = expectOk(pool.health.expect, res.status);
    } catch (e) { ok = false; }
    clearTimeout(timer);   // otherwise the pending timer keeps this instance alive
    if (ok) hc.set(key, 0);
}

async function health() {
    const hc = ngx.shared.pcdn_hc, t = now(), jobs = [];
    Object.keys(S).forEach(function (id) {
        const site = S[id];
        if (!site) return;
        Object.keys(site.pools).forEach(function (name) {
            const pool = site.pools[name];
            if (!pool.health.enabled) return;
            pool.origins.forEach(function (o) {
                const nk = 'n|' + hcKey(site, pool, o);
                if ((hc.get(nk) || 0) > t) return;
                hc.set(nk, t + pool.health.interval);
                jobs.push(checkOrigin(site, pool, o));
            });
        });
    });
    await Promise.all(jobs);
}

// ------------------------------------------------------------------ image resize parameters

function imgParams(r) {
    const site = siteOf(r);
    if (!site || !site.image || !/\.(?:jpe?g|png|gif|webp)$/i.test(r.uri) || inTunnel(site, r.uri)) return null;
    const dim = function (v) {
        if (!/^\d{1,5}$/.test(String(v || ''))) return '-';
        return String(Math.min(site.image.max, Math.max(1, +v)));
    };
    const w = dim(r.args.width), h = dim(r.args.height);
    if (w === '-' && h === '-') return null;
    return { w: w, h: h, q: String(site.image.quality) };
}
function imgW(r) { const p = imgParams(r); return p ? p.w : ''; }
function imgH(r) { const p = imgParams(r); return p ? p.h : ''; }
function imgQ(r) { const p = imgParams(r); return p ? p.q : ''; }

// ------------------------------------------------------------------ pages

const CSS = 'body{margin:0;min-height:100vh;display:grid;place-items:center;font-family:Tahoma,Vazirmatn,sans-serif;background:#f5f7fb;color:#1f2937}'
    + '.box{max-width:460px;padding:32px;background:#fff;border-radius:16px;box-shadow:0 10px 30px #0001;text-align:center}'
    + 'h1{font-size:20px;margin:0 0 12px}p{line-height:1.9;color:#4b5563;margin:0}.en{margin-top:16px;font-size:13px}'
    + '.meta{margin-top:18px;font-size:12px;color:#9ca3af;direction:ltr}input,button{font:inherit;padding:8px 12px;border-radius:8px;border:1px solid #d1d5db}'
    + 'button{background:#2563eb;color:#fff;border:0;cursor:pointer}.err{color:#b91c1c}svg{background:#f3f4f6;border-radius:8px;margin:12px 0}';

function page(title, bodyFa, en, extra, meta) {
    return '<!doctype html>\n<html lang="fa" dir="rtl">\n<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
        + '<meta name="robots" content="noindex"><title>' + esc(title) + '</title><style>' + CSS + '</style></head>\n'
        + '<body><div class="box"><h1>' + esc(title) + '</h1><p>' + bodyFa + '</p>' + (extra || '')
        + '<p dir="ltr" class="en">' + esc(en) + '</p>'
        + (meta ? '<div class="meta">' + esc(meta) + '</div>' : '') + '</div></body></html>\n';
}

function send(r, code, html, headers) {
    r.headersOut['Content-Type'] = 'text/html; charset=utf-8';
    r.headersOut['Cache-Control'] = 'no-store';
    Object.keys(headers || {}).forEach(function (k) { r.headersOut[k] = headers[k]; });
    r.return(code, html);
}

function safeReturn(u) {
    u = String(u || '/');
    if (u.charAt(0) !== '/' || u.charAt(1) === '/' || u.charAt(1) === '\\' || /[\r\n]/.test(u) || u.length > 4096) return '/';
    return u;
}

function metaLine(r, v) {
    return 'ref ' + v + ' · ip ' + r.variables.remote_addr + ' · ' + new Date().toISOString().substring(0, 19) + 'Z';
}

function deny(r) {
    const v = String(r.variables.pcdn_verdict || 'block:firewall:x');
    const p = v.split(':'), action = p[0], source = p[1] || '', rule = p[2] || '';
    const site = siteOf(r);
    if (site && action === 'challenge') return challengePage(r, site, v);
    if (site && action === 'captcha') return captchaPage(r, site, safeReturn(r.variables.request_uri), '', v);
    if (source === 'ratelimit') {
        let retry = 60;
        if (site) {
            const until = ngx.shared.pcdn_blk.get('b:' + site.id + ':' + rule + ':' + r.variables.remote_addr) || 0;
            retry = Math.max(1, until - now());
        }
        return send(r, 429, page('درخواست‌های بیش از حد', 'تعداد درخواست‌های شما از حد مجاز بیشتر شده است. لطفاً کمی بعد دوباره تلاش کنید.',
            'Too many requests. Please try again later.', '', metaLine(r, v)), { 'Retry-After': String(retry) });
    }
    return send(r, 403, page('دسترسی مسدود شد', 'درخواست شما توسط سامانه امنیتی CDN مسدود شد. اگر فکر می‌کنید اشتباهی رخ داده، با مدیر وب‌سایت تماس بگیرید.',
        'Access denied by the website\'s security settings.', '', metaLine(r, v)));
}

// ---- JS proof-of-work challenge

// token = exp.nonce.difficulty.sig — bound to client ip + user agent
function powSig(site, ip, ua, exp, nonce, diff) { return hmac(site.secret, 'chal|' + ip + '|' + ua + '|' + exp + '|' + nonce + '|' + diff); }

// minimal SHA-256 (ASCII input) so the page also works on plain-http sites without crypto.subtle
const PAGE_SHA256 = 'function S(m){var K=[],H=[],c={},p=2,i,j,w=[],r="";for(;K.length<64;p++)if(!c[p]){for(i=0;i<313;i+=p)c[i]=p;'
    + 'H.push(Math.pow(p,.5)*4294967296|0);K.push(Math.pow(p,1/3)*4294967296|0)}var h=H.slice(0,8),L=m.length*8;m+="\\x80";'
    + 'while(m.length%64-56)m+="\\x00";for(i=0;i<m.length;i++)w[i>>2]|=m.charCodeAt(i)<<((3-i)%4)*8;w[w.length]=L/4294967296|0;w[w.length]=L;'
    + 'function R(v,n){return v>>>n|v<<32-n}for(j=0;j<w.length;){var W=w.slice(j,j+=16),o=h;h=h.slice(0,8);for(i=0;i<64;i++){var a=W[i-15],b=W[i-2],'
    + 'A=h[0],E=h[4],t1=h[7]+(R(E,6)^R(E,11)^R(E,25))+(E&h[5]^~E&h[6])+K[i]+(W[i]=i<16?W[i]:W[i-16]+(R(a,7)^R(a,18)^a>>>3)+W[i-7]+(R(b,17)^R(b,19)^b>>>10)|0),'
    + 't2=(R(A,2)^R(A,13)^R(A,22))+(A&h[1]^A&h[2]^h[1]&h[2]);h=[t1+t2|0].concat(h);h[4]=h[4]+t1|0}for(i=0;i<8;i++)h[i]=h[i]+o[i]|0}'
    + 'for(i=0;i<8;i++)for(j=3;j+1;j--){var x=h[i]>>j*8&255;r+=(x<16?"0":"")+x.toString(16)}return r}';

function challengePage(r, site, v) {
    const exp = now() + TOKEN_TTL, nonce = randHex(16), ip = r.variables.remote_addr, ua = String(r.headersIn['User-Agent'] || '');
    const token = exp + '.' + nonce + '.' + POW_DIFFICULTY + '.' + powSig(site, ip, ua, exp, nonce, POW_DIFFICULTY);
    const data = JSON.stringify({ t: token, n: nonce, d: POW_DIFFICULTY, r: safeReturn(r.variables.request_uri) }).replace(/</g, '\\u003c');
    const script = '<script id="pcdn-challenge" type="application/json">' + data + '</script><script>' + PAGE_SHA256
        + ';(function(){var c=JSON.parse(document.getElementById("pcdn-challenge").textContent),z=new Array(c.d+1).join("0"),n=0;'
        + 'function step(){for(var k=0;k<5000;k++,n++){if(S(c.n+":"+n).slice(0,c.d)===z){location.replace("/__pcdn/verify?t="+encodeURIComponent(c.t)+"&n="+n+"&r="+encodeURIComponent(c.r));return}}setTimeout(step,0)}step()})()</script>'
        + '<noscript><p class="err">برای ادامه باید جاوااسکریپت مرورگر فعال باشد.</p></noscript>';
    send(r, 403, page('در حال بررسی مرورگر شما…', 'این بررسی خودکار چند ثانیه طول می‌کشد و از وب‌سایت در برابر حملات محافظت می‌کند.',
        'Checking your browser before accessing the website…', script, metaLine(r, v)));
}

function verify(r) {
    const site = siteOf(r);
    if (!site) return r.return(404);
    const a = r.args, ip = r.variables.remote_addr, ua = String(r.headersIn['User-Agent'] || '');
    const back = safeReturn(a.r);
    const p = String(a.t || '').split('.');
    const n = String(a.n || '');
    let ok = p.length === 4 && +p[0] > now() && +p[2] >= POW_DIFFICULTY && /^\d{1,12}$/.test(n)
        && safeEq(p[3], powSig(site, ip, ua, p[0], p[1], p[2]))
        && sha256(p[1] + ':' + n).substring(0, +p[2]) === new Array(+p[2] + 1).join('0');
    ok = ok && useOnce('pv:' + p[1], +p[0]);
    if (!ok) {
        return send(r, 403, page('بررسی ناموفق بود', 'تأیید مرورگر انجام نشد. <a href="' + esc(back) + '">دوباره تلاش کنید</a>.',
            'Browser verification failed. Please try again.', '', ''));
    }
    grant(r, site, 'js', back);
}

function useOnce(key, exp) {
    const blk = ngx.shared.pcdn_blk;
    if (blk.get(key)) return false;
    blk.set(key, exp);
    return true;
}

function grant(r, site, level, back) {
    const ip = r.variables.remote_addr, ua = String(r.headersIn['User-Agent'] || '');
    const exp = now() + site.ddos.ttl;
    const val = exp + '.' + level + '.' + clrSig(site, ip, ua, String(exp), level);
    r.headersOut['Set-Cookie'] = CLR_COOKIE + '=' + val + '; Path=/; Max-Age=' + site.ddos.ttl + '; HttpOnly; SameSite=Lax'
        + (r.variables.scheme === 'https' ? '; Secure' : '');
    r.headersOut['Cache-Control'] = 'no-store';
    r.return(302, back);
}

// ---- captcha: distorted stroke glyphs in SVG; the answer is derived from HMAC(secret, nonce)
// so nothing is stored server side and the token alone cannot reveal it.

const GLYPHS = {
    A: [[0, 6, 2, 0, 4, 6], [1, 3.5, 3, 3.5]], C: [[4, 1, 3, 0, 1, 0, 0, 1, 0, 5, 1, 6, 3, 6, 4, 5]],
    E: [[4, 0, 0, 0, 0, 6, 4, 6], [0, 3, 3, 3]], F: [[4, 0, 0, 0, 0, 6], [0, 3, 3, 3]],
    H: [[0, 0, 0, 6], [4, 0, 4, 6], [0, 3, 4, 3]], K: [[0, 0, 0, 6], [4, 0, 0, 3.5], [1.5, 2.5, 4, 6]],
    L: [[0, 0, 0, 6, 4, 6]], M: [[0, 6, 0, 0, 2, 3, 4, 0, 4, 6]], N: [[0, 6, 0, 0, 4, 6, 4, 0]],
    P: [[0, 6, 0, 0, 3, 0, 4, 1, 4, 2, 3, 3, 0, 3]], R: [[0, 6, 0, 0, 3, 0, 4, 1, 4, 2, 3, 3, 0, 3], [2, 3, 4, 6]],
    T: [[0, 0, 4, 0], [2, 0, 2, 6]], U: [[0, 0, 0, 5, 1, 6, 3, 6, 4, 5, 4, 0]], V: [[0, 0, 2, 6, 4, 0]],
    W: [[0, 0, 1, 6, 2, 2, 3, 6, 4, 0]], X: [[0, 0, 4, 6], [4, 0, 0, 6]], Y: [[0, 0, 2, 3, 4, 0], [2, 3, 2, 6]],
    Z: [[0, 0, 4, 0, 0, 6, 4, 6]], 3: [[0, 0, 4, 0, 2, 2.5, 4, 4, 3, 6, 1, 6, 0, 5]], 4: [[3, 6, 3, 0, 0, 4, 4, 4]],
    7: [[0, 0, 4, 0, 1, 6]],
};

function captchaAnswer(site, nonce) {
    const h = hmac(site.secret, 'capans|' + nonce);
    let a = '';
    for (let i = 0; i < CAPTCHA_LEN; i++) a += CAPTCHA_ALPHABET.charAt(parseInt(h.substring(i * 4, i * 4 + 4), 16) % CAPTCHA_ALPHABET.length);
    return a;
}

function capSig(site, ip, ua, exp, nonce) { return hmac(site.secret, 'cap|' + ip + '|' + ua + '|' + exp + '|' + nonce); }

function rnd(a, b) { return a + Math.random() * (b - a); }
function f1(x) { return (Math.round(x * 10) / 10).toString(); }

function captchaSvg(text) {
    const W = 230, Hh = 76;
    let out = '<svg xmlns="http://www.w3.org/2000/svg" width="' + W + '" height="' + Hh + '" viewBox="0 0 ' + W + ' ' + Hh + '" role="img" aria-label="captcha">';
    for (let i = 0; i < 5; i++) {
        out += '<path d="M' + f1(rnd(0, 40)) + ' ' + f1(rnd(5, 70)) + ' Q' + f1(rnd(60, 170)) + ' ' + f1(rnd(-20, 96)) + ' ' + f1(rnd(190, 230)) + ' ' + f1(rnd(5, 70))
            + '" stroke="#' + ['9ca3af', 'a5b4fc', 'fca5a5', '86efac'][i % 4] + '" stroke-width="' + f1(rnd(1, 2.5)) + '" fill="none"/>';
    }
    for (let i = 0; i < text.length; i++) {
        const s = rnd(6.5, 8), ox = 22 + i * 40 + rnd(-4, 4), oy = 14 + rnd(-6, 6), rot = rnd(-28, 28), sk = rnd(-15, 15);
        const col = ['1f2937', '1e3a8a', '7c2d12', '14532d', '581c87'][Math.floor(rnd(0, 5))];
        let d = '';
        GLYPHS[text.charAt(i)].forEach(function (line) {
            for (let j = 0; j < line.length; j += 2) d += (j ? 'L' : 'M') + f1(line[j] * s + rnd(-2, 2)) + ' ' + f1(line[j + 1] * s + rnd(-2, 2));
        });
        out += '<path transform="translate(' + f1(ox) + ' ' + f1(oy) + ') rotate(' + f1(rot) + ' 14 22) skewX(' + f1(sk) + ')" d="' + d
            + '" stroke="#' + col + '" stroke-width="' + f1(rnd(2.6, 3.6)) + '" fill="none" stroke-linecap="round" stroke-linejoin="round"/>';
    }
    for (let i = 0; i < 40; i++) out += '<circle cx="' + f1(rnd(0, W)) + '" cy="' + f1(rnd(0, Hh)) + '" r="' + f1(rnd(0.6, 1.8)) + '" fill="#6b7280"/>';
    return out + '</svg>';
}

function captchaPage(r, site, back, err, v) {
    const exp = now() + TOKEN_TTL, nonce = randHex(16), ip = r.variables.remote_addr, ua = String(r.headersIn['User-Agent'] || '');
    const token = exp + '.' + nonce + '.' + capSig(site, ip, ua, exp, nonce);
    const form = '<div>' + captchaSvg(captchaAnswer(site, nonce)) + '</div>'
        + (err ? '<p class="err">' + err + '</p>' : '')
        + '<form method="post" action="/__pcdn/captcha"><input type="hidden" name="t" value="' + esc(token) + '">'
        + '<input type="hidden" name="r" value="' + esc(back) + '">'
        + '<input name="a" autocomplete="off" autofocus required maxlength="12" dir="ltr" placeholder="کد تصویر"> '
        + '<button type="submit">تأیید</button></form>';
    send(r, 403, page('لطفاً کد امنیتی را وارد کنید', 'برای ادامه، حروف و اعداد تصویر زیر را وارد کنید.',
        'Please type the characters shown in the image to continue.', form, v ? metaLine(r, v) : ''));
}

function parseForm(body) {
    const out = {};
    String(body || '').split('&').forEach(function (kv) {
        const i = kv.indexOf('=');
        if (i > 0) out[pctDecode(kv.substring(0, i).replace(/\+/g, ' '))] = pctDecode(kv.substring(i + 1).replace(/\+/g, ' '));
    });
    return out;
}

function captcha(r) {
    const site = siteOf(r);
    if (!site) return r.return(404);
    if (r.method !== 'POST') return r.return(405);
    const f = parseForm(r.requestText), ip = r.variables.remote_addr, ua = String(r.headersIn['User-Agent'] || '');
    const back = safeReturn(f.r), p = String(f.t || '').split('.');
    // any attempt burns the token (one guess per image), then the answer is compared
    const ok = p.length === 3 && +p[0] > now() && safeEq(p[2], capSig(site, ip, ua, p[0], p[1]))
        && useOnce('pc:' + p[1], +p[0])
        && safeEq(String(f.a || '').trim().toUpperCase(), captchaAnswer(site, p[1]));
    if (!ok) return captchaPage(r, site, back, 'کد وارد شده صحیح نیست. دوباره تلاش کنید. (Incorrect code)', '');
    grant(r, site, 'cap', back);
}

export default { verdict, upstream, tunnelUpstream, imgW, imgH, imgQ, deny, verify, captcha, health };
