#!/usr/bin/env bash
# Restrict the ns2 PowerDNS API (port 8081) to the controller's IP.
#
# Docker publishes container ports with its own iptables rules, which bypass ufw:
# a "ufw allow from X to any port 8081" rule does NOT protect a published port.
# The DOCKER-USER chain is the supported place for such filtering. This script adds
# the rules and installs a systemd unit so they are re-applied after every reboot or
# Docker restart.
#   sudo deploy/ns2-firewall.sh <controller-ip> [<controller-ip> ...]
set -euo pipefail
[ "$(id -u)" -eq 0 ] || { echo "run as root"; exit 1; }
[ $# -ge 1 ] || { echo "usage: $0 <controller-ip> [...]"; exit 1; }
for ip in "$@"; do
  [[ "$ip" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]] || { echo "not an IPv4 address: $ip"; exit 1; }
done
PORT=8081
RULES=/usr/local/sbin/pcdn-ns2-firewall

cat > "$RULES" <<RULESEOF
#!/bin/sh
# generated by deploy/ns2-firewall.sh — allowed: $*
set -e
# IPv4 (required): allow the controller, drop everyone else
iptables -N PCDN-NS2 2>/dev/null || iptables -F PCDN-NS2
iptables -C DOCKER-USER -j PCDN-NS2 2>/dev/null || iptables -I DOCKER-USER -j PCDN-NS2
for ip in $*; do
  iptables -A PCDN-NS2 -p tcp -m conntrack --ctorigdstport $PORT -s "\$ip" -j RETURN
done
iptables -A PCDN-NS2 -p tcp -m conntrack --ctorigdstport $PORT -j DROP
# IPv6 (best effort; only exists when Docker manages ip6tables): drop all
if command -v ip6tables >/dev/null 2>&1 && ip6tables -L DOCKER-USER -n >/dev/null 2>&1; then
  ip6tables -N PCDN-NS2 2>/dev/null || ip6tables -F PCDN-NS2
  ip6tables -C DOCKER-USER -j PCDN-NS2 2>/dev/null || ip6tables -I DOCKER-USER -j PCDN-NS2
  ip6tables -A PCDN-NS2 -p tcp -m conntrack --ctorigdstport $PORT -j DROP
fi
RULESEOF
chmod 755 "$RULES"

cat > /etc/systemd/system/pcdn-ns2-firewall.service <<UNITEOF
[Unit]
Description=Pasargad CDN: restrict the ns2 PowerDNS API to the controller
After=docker.service
Requires=docker.service
PartOf=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=$RULES

[Install]
WantedBy=multi-user.target docker.service
UNITEOF
systemctl daemon-reload
systemctl enable --now pcdn-ns2-firewall.service >/dev/null
systemctl restart pcdn-ns2-firewall.service
echo "PowerDNS API (tcp/$PORT) now only accepts: $*"
iptables -S PCDN-NS2
