#!/bin/sh
# Renders the environment-dependent parts of the monitoring config, then execs the real binary.
#
#   render-config.sh prometheus   [args...]  -> /prometheus/rendered/*.json (file_sd targets)
#   render-config.sh alertmanager [args...]  -> /alertmanager/rendered/alertmanager.yml
#
# Runs inside the official prom/* images (busybox sh + sed). Secrets are NEVER copied into the
# rendered files: Prometheus reads /run/secrets/metrics_token, Alertmanager reads
# /run/secrets/telegram_bot_token and /run/secrets/smtp_password themselves (*_file settings).
#
# Local dry run (validation / CI):
#   RENDER_ONLY=1 RENDER_DIR=/tmp/out SECRETS_DIR=/tmp/secrets CONTROLLER_URL=https://x \
#     sh render-config.sh prometheus
set -eu

SECRETS_DIR="${SECRETS_DIR:-/run/secrets}"
what="${1:-}"
[ $# -gt 0 ] && shift

die() { echo "render-config: $*" >&2; exit 1; }
log() { echo "render-config: $*" >&2; }

# YAML/JSON double-quoted string body: escape backslash and double quote
q() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

# reject URLs that could break out of a quoted string or carry credentials
check_url() {
  case "$1" in
    http://*|https://*) ;;
    *) die "$2 must start with http:// or https:// (got '$1')" ;;
  esac
  case "$1" in
    *'"'*|*'\'*|*' '*|*@*) die "$2 contains a forbidden character (quote, backslash, space or '@')" ;;
  esac
}

# file_sd JSON with one target per argument; labels come from $SD_LABELS (already JSON pairs)
write_sd() {
  out="$1"; shift
  {
    printf '['
    sep=''
    for t in "$@"; do
      printf '%s{"targets":["%s"],"labels":{%s}}' "$sep" "$(q "$t")" "$SD_LABELS"
      sep=','
    done
    printf ']\n'
  } > "$out.tmp"
  mv "$out.tmp" "$out"
}

render_prometheus() {
  dir="${RENDER_DIR:-/prometheus/rendered}"
  mkdir -p "$dir"
  url="${CONTROLLER_URL:-}"
  [ -n "$url" ] || die "CONTROLLER_URL is required"
  check_url "$url" CONTROLLER_URL
  url="${url%/}"
  scheme="${url%%://*}"
  rest="${url#*://}"
  hostport="${rest%%/*}"
  prefix=""
  [ "$rest" != "$hostport" ] && prefix="/${rest#*/}"

  SD_LABELS="\"__scheme__\":\"$scheme\",\"__metrics_path__\":\"$(q "$prefix")/metrics\",\"instance\":\"$(q "$hostport")\""
  write_sd "$dir/controller.json" "$hostport"

  # blackbox targets: liveness, deep health, public status JSON
  SD_LABELS='"probe":"healthz","component":"controller"'
  write_sd "$dir/probe-healthz.json" "$url/healthz"
  SD_LABELS='"probe":"healthz_deep","component":"controller"'
  write_sd "$dir/probe-deep.json" "$url/healthz/deep"
  SD_LABELS='"probe":"status_json","component":"controller"'
  write_sd "$dir/probe-status-json.json" "$url/status.json"

  # the separately hosted status page (deploy/status) and its mirrored JSON
  if [ -n "${STATUS_PAGE_URL:-}" ]; then
    check_url "$STATUS_PAGE_URL" STATUS_PAGE_URL
    sp="${STATUS_PAGE_URL%/}"
    SD_LABELS='"probe":"status_page","component":"status_page"'
    write_sd "$dir/probe-status-page.json" "$sp/" "$sp/status.json"
  else
    SD_LABELS=''
    write_sd "$dir/probe-status-page.json"
  fi

  # extra HTTPS endpoints (e.g. the HA standby controller, WHMCS): space separated
  set --
  for u in ${PROBE_EXTRA_URLS:-}; do check_url "$u" PROBE_EXTRA_URLS; set -- "$@" "$u"; done
  SD_LABELS='"probe":"extra","component":"extra"'
  write_sd "$dir/probe-extra.json" "$@"

  # optional admin-API bridge (json-exporter, compose profile api-bridge)
  SD_LABELS='"bridge":"overview"'
  if [ "${PCDN_API_BRIDGE:-0}" = "1" ]; then
    write_sd "$dir/bridge-overview.json" "$url/api/v1/overview"
    SD_LABELS='"bridge":"analytics"'
    write_sd "$dir/bridge-analytics.json" "$url/api/v1/analytics?period=24h"
  else
    write_sd "$dir/bridge-overview.json"
    write_sd "$dir/bridge-analytics.json"
  fi

  # the bearer token file must exist (an empty one is fine when METRICS_TOKEN is unset)
  [ -e "$SECRETS_DIR/metrics_token" ] || log "warning: $SECRETS_DIR/metrics_token missing"
  log "prometheus targets rendered into $dir (controller $scheme://$hostport$prefix)"
}

render_alertmanager() {
  dir="${RENDER_DIR:-/alertmanager/rendered}"
  mkdir -p "$dir"
  out="$dir/alertmanager.yml"

  tg=0
  if [ -s "$SECRETS_DIR/telegram_bot_token" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then tg=1; fi
  mail=0
  if [ -n "${ALERT_EMAIL_TO:-}" ] && [ -n "${SMTP_SMARTHOST:-}" ] && [ -n "${SMTP_FROM:-}" ]; then mail=1; fi
  [ $tg = 1 ] || [ $mail = 1 ] || log "warning: no Telegram or e-mail channel configured; alerts are only visible in the Alertmanager UI"

  api="${TELEGRAM_API_URL:-https://api.telegram.org}"
  check_url "$api" TELEGRAM_API_URL
  [ -z "${ALERT_HTTPS_PROXY:-}" ] || check_url "$ALERT_HTTPS_PROXY" ALERT_HTTPS_PROXY

  {
    echo "# GENERATED by render-config.sh at container start — edit the environment, not this file."
    echo "global:"
    echo "  resolve_timeout: 5m"
    if [ $mail = 1 ]; then
      echo "  smtp_from: \"$(q "$SMTP_FROM")\""
      echo "  smtp_smarthost: \"$(q "$SMTP_SMARTHOST")\""
      echo "  smtp_require_tls: ${SMTP_REQUIRE_TLS:-true}"
      if [ -n "${SMTP_USERNAME:-}" ]; then
        echo "  smtp_auth_username: \"$(q "$SMTP_USERNAME")\""
        [ -s "$SECRETS_DIR/smtp_password" ] && echo "  smtp_auth_password_file: \"$SECRETS_DIR/smtp_password\""
      fi
    fi
    echo "templates:"
    echo "  - /etc/alertmanager/templates/*.tmpl"
    cat <<'EOF'
route:
  receiver: pcdn
  group_by: [alertname, severity]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 6h
  routes:
    - matchers: ['severity="critical"']
      receiver: pcdn
      group_wait: 10s
      repeat_interval: 1h
    - matchers: ['severity="info"']
      receiver: pcdn-chat
      repeat_interval: 24h
inhibit_rules:
  # controller unreachable: every alert derived from its /metrics is noise
  - source_matchers: ['alertname=~"PcdnControllerDown|PcdnControllerScrapeFailing"']
    target_matchers: ['source="metrics"']
  # all edges down: the single-edge / degraded alerts add nothing
  - source_matchers: ['alertname="PcdnEdgesAllOffline"']
    target_matchers: ['alertname=~"PcdnEdgesOffline|PcdnEdgeOffline|PcdnEdgesProbeFailing"']
  - source_matchers: ['severity="critical"']
    target_matchers: ['severity="warning"']
    equal: [alertname]
receivers:
EOF
    for name in pcdn pcdn-chat; do
      echo "  - name: $name"
      if [ $tg = 1 ]; then
        echo "    telegram_configs:"
        old_ifs="$IFS"; IFS=','
        for chat in $TELEGRAM_CHAT_ID; do
          chat="$(echo "$chat" | tr -d ' ')"
          case "$chat" in ''|*[!0-9-]*) die "TELEGRAM_CHAT_ID must be numeric ids separated by commas" ;; esac
          echo "      - bot_token_file: \"$SECRETS_DIR/telegram_bot_token\""
          echo "        chat_id: $chat"
          echo "        api_url: \"$(q "$api")\""
          echo "        parse_mode: HTML"
          echo "        send_resolved: true"
          echo "        message: '{{ template \"pcdn.telegram.message\" . }}'"
          if [ -n "${ALERT_HTTPS_PROXY:-}" ]; then
            echo "        http_config:"
            echo "          proxy_url: \"$(q "$ALERT_HTTPS_PROXY")\""
          fi
        done
        IFS="$old_ifs"
      fi
      # e-mail for the main receiver, and for info alerts only when there is no Telegram
      if [ $mail = 1 ] && { [ $name = pcdn ] || [ $tg = 0 ]; }; then
        echo "    email_configs:"
        echo "      - to: \"$(q "$ALERT_EMAIL_TO")\""
        echo "        send_resolved: true"
        echo "        headers:"
        echo "          Subject: '{{ template \"pcdn.email.subject\" . }}'"
        echo "        html: '{{ template \"pcdn.email.html\" . }}'"
      fi
    done
  } > "$out.tmp"
  mv "$out.tmp" "$out"
  log "alertmanager config rendered into $out (telegram=$tg email=$mail)"
}

case "$what" in
  prometheus)   render_prometheus;   [ -n "${RENDER_ONLY:-}" ] || exec /bin/prometheus "$@" ;;
  alertmanager) render_alertmanager; [ -n "${RENDER_ONLY:-}" ] || exec /bin/alertmanager "$@" ;;
  *) die "usage: render-config.sh prometheus|alertmanager [args...]" ;;
esac
