#!/usr/bin/env python3
"""Pasargad CDN edge agent.

Pulls site configuration from the controller, renders nginx vhosts, installs
certificates, executes cache purges and reports per-host bandwidth.
Standard library only, so it runs on any stock Debian/Ubuntu python3.
"""

import hashlib
import json
import logging
import os
import re
import shutil
import signal
import subprocess
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone

log = logging.getLogger("pcdn-agent")

DEFAULTS = {
    "CONTROLLER_URL": "",
    "EDGE_TOKEN": "",
    "NGINX_DIR": "/etc/nginx/pcdn",
    "CACHE_DIR": "/var/cache/pcdn",
    "STATE_FILE": "/var/lib/pcdn/state.json",
    "ACCESS_LOG": "/var/log/nginx/pcdn-access.log",
    "PAGES_DIR": "/usr/share/pcdn/pages",
    "CACHE_MAX_SIZE": "10g",
    "CACHE_KEYS_ZONE": "5m",
    "CACHE_INACTIVE": "7d",
    "NGINX_TEST_CMD": "nginx -t -q",
    "NGINX_RELOAD_CMD": "nginx -s reload",
    "NGINX_USER": "www-data",
    "LISTEN_IPV6": "yes",
    "POLL_INTERVAL": "20",
    "USAGE_INTERVAL": "60",
}

STATIC_EXT = "css|js|mjs|map|jpg|jpeg|png|gif|webp|avif|svg|ico|bmp|woff|woff2|ttf|eot|otf|mp4|webm|mp3|ogg|pdf|zip|gz|rar|7z|txt|xml|json"
SAFE_NAME = re.compile(r"^[a-z0-9*][a-z0-9.*-]*$")
SAFE_ORIGIN = re.compile(r"^(\[[0-9a-f:]+\]|[a-z0-9][a-z0-9.-]*)$")


def load_config(path: str) -> dict:
    cfg = dict(DEFAULTS)
    if os.path.exists(path):
        with open(path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                cfg[k.strip()] = v.strip().strip('"').strip("'")
    for k in DEFAULTS:
        if os.getenv("PCDN_" + k):
            cfg[k] = os.environ["PCDN_" + k]
    return cfg


# ----------------------------------------------------------------- rendering

def _q(s: str) -> str:
    """Quote a value for nginx config (values are validated, this is defence in depth)."""
    return '"' + s.replace("\\", "").replace('"', "").replace("$", "").replace("\n", "") + '"'


def render_site(site: dict, cfg: dict) -> tuple[str, dict]:
    """Return (nginx config text, {relative_path: content}) for one site."""
    sid = int(site["id"])
    domain = site["domain"]
    files = {}
    zone = f"pcdn_{sid}"
    cache_path = os.path.join(cfg["CACHE_DIR"], str(sid))
    out = [f"# {domain} (site {sid}) — generated by pcdn-agent, do not edit"]
    out.append(
        f"proxy_cache_path {cache_path} levels=1:2 keys_zone={zone}:{cfg['CACHE_KEYS_ZONE']} "
        f"max_size={cfg['CACHE_MAX_SIZE']} inactive={cfg['CACHE_INACTIVE']} use_temp_path=off;"
    )
    rps = int(site.get("rate_limit_rps") or 0)
    if rps > 0:
        out.append(f"limit_req_zone $binary_remote_addr zone=pcdn_rl_{sid}:1m rate={rps}r/s;")

    ssl = site.get("ssl")
    if ssl:
        files[f"certs/{sid}.crt"] = ssl["cert"]
        files[f"certs/{sid}.key"] = ssl["key"]

    status = site.get("status", "active")
    blocked = site.get("blocked_ips") or []
    proto = "https" if site.get("origin_protocol") == "https" else "http"
    edge_ttl = int(site.get("edge_cache_ttl") or 0)
    browser_ttl = int(site.get("browser_cache_ttl") or 0)
    cache_on = bool(site.get("cache_enabled")) and edge_ttl >= 0
    v6 = cfg.get("LISTEN_IPV6", "yes").lower() in ("1", "yes", "true", "on")

    for host in site["hosts"]:
        name, origin = host["name"].lower(), host["origin"].lower()
        if not SAFE_NAME.match(name) or not SAFE_ORIGIN.match(origin):
            log.warning("skipping unsafe host entry %r -> %r", name, origin)
            continue
        s = ["server {"]
        s.append("    listen 80;")
        if v6:
            s.append("    listen [::]:80;")
        if ssl:
            # "listen ... http2" works on every nginx >= 1.9.5 (newer ones only warn)
            s.append("    listen 443 ssl http2;")
            if v6:
                s.append("    listen [::]:443 ssl http2;")
            s.append(f"    ssl_certificate {cfg['NGINX_DIR']}/certs/{sid}.crt;")
            s.append(f"    ssl_certificate_key {cfg['NGINX_DIR']}/certs/{sid}.key;")
        s.append(f"    server_name {name};")
        s.append(f"    access_log {cfg['ACCESS_LOG']} pcdn;")
        s.append("    location = /__pcdn/health { access_log off; return 200 \"ok\\n\"; }")

        if status in ("suspended", "over_quota"):
            page = "suspended.html" if status == "suspended" else "over_quota.html"
            s.append(f"    root {cfg['PAGES_DIR']};")
            s.append(f"    error_page 503 /{page};")
            s.append(f"    location = /{page} {{ internal; add_header Cache-Control no-store always; }}")
            s.append("    location / { return 503; }")
            s.append("}")
            out.append("\n".join(s))
            continue

        for ip in blocked:
            s.append(f"    deny {ip};")
        if site.get("force_https") and ssl:
            s.append("    if ($scheme = http) { return 301 https://$host$request_uri; }")
        if rps > 0:
            s.append(f"    limit_req zone=pcdn_rl_{sid} burst={rps * 2} nodelay;")
            s.append("    limit_req_status 429;")

        s.append(f"    set $pcdn_origin {_q(origin)};")
        s.append("    proxy_set_header Host $host;")
        s.append("    proxy_set_header X-Real-IP $remote_addr;")
        s.append("    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
        s.append("    proxy_set_header X-Forwarded-Proto $scheme;")
        s.append("    proxy_set_header Upgrade $http_upgrade;")
        s.append("    proxy_set_header Connection $pcdn_connection_upgrade;")
        s.append("    proxy_ssl_server_name on;")
        s.append("    proxy_ssl_name $host;")

        common_headers = "        add_header X-Cache $upstream_cache_status always;\n        add_header X-Served-By $hostname always;"
        if cache_on:
            s.append("    proxy_cache_key $scheme://$host$request_uri;")
            # dynamic content: honour origin Cache-Control / Set-Cookie
            s.append("    location / {")
            s.append(f"        proxy_cache {zone};")
            s.append("        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;")
            s.append("        proxy_cache_lock on;")
            s.append("        proxy_cache_background_update on;")
            s.append(f"        proxy_pass {proto}://$pcdn_origin;")
            s.append(common_headers)
            s.append("    }")
            # static assets: cached at the edge even without origin headers
            s.append(f"    location ~* \\.(?:{STATIC_EXT})$ {{")
            s.append(f"        proxy_cache {zone};")
            s.append(f"        proxy_cache_valid 200 206 301 {max(edge_ttl, 60)}s;")
            s.append("        proxy_cache_valid 404 1m;")
            s.append("        proxy_ignore_headers Cache-Control Expires Set-Cookie Vary;")
            s.append("        proxy_hide_header Set-Cookie;")
            s.append("        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;")
            s.append("        proxy_cache_lock on;")
            s.append("        proxy_cache_background_update on;")
            if browser_ttl > 0:
                s.append("        proxy_hide_header Cache-Control;")
                s.append("        proxy_hide_header Expires;")
                s.append(f"        add_header Cache-Control \"public, max-age={browser_ttl}\" always;")
            s.append(f"        proxy_pass {proto}://$pcdn_origin;")
            s.append(common_headers)
            s.append("    }")
        else:
            s.append("    location / {")
            s.append(f"        proxy_pass {proto}://$pcdn_origin;")
            s.append("        add_header X-Cache BYPASS always;")
            s.append("        add_header X-Served-By $hostname always;")
            s.append("    }")
        s.append("}")
        out.append("\n".join(s))

    return "\n\n".join(out) + "\n", files


def render_all(config: dict, cfg: dict) -> dict:
    files = {}
    for site in config.get("sites", []):
        text, extra = render_site(site, cfg)
        files[f"sites/{int(site['id'])}.conf"] = text
        files.update(extra)
    return files


# ----------------------------------------------------------------- apply

def run(cmd: str) -> tuple[int, str]:
    p = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return p.returncode, (p.stdout + p.stderr).strip()


def write_tree(root: str, files: dict):
    os.makedirs(os.path.join(root, "sites"), exist_ok=True)
    os.makedirs(os.path.join(root, "certs"), mode=0o700, exist_ok=True)
    for rel, content in files.items():
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        mode = 0o600 if rel.endswith(".key") else 0o644
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode)
        with os.fdopen(fd, "w") as f:
            f.write(content)


def ensure_cache_dirs(config: dict, cfg: dict):
    base = cfg["CACHE_DIR"]
    os.makedirs(base, exist_ok=True)
    wanted = {str(int(s["id"])) for s in config.get("sites", [])}
    for sid in wanted:
        os.makedirs(os.path.join(base, sid), exist_ok=True)
        try:
            shutil.chown(os.path.join(base, sid), user=cfg["NGINX_USER"])
        except (LookupError, PermissionError, OSError):
            pass
    for name in os.listdir(base):
        if name.isdigit() and name not in wanted:
            shutil.rmtree(os.path.join(base, name), ignore_errors=True)


def apply_config(config: dict, cfg: dict) -> str | None:
    """Atomically swap the rendered tree in; roll back if nginx rejects it."""
    root = cfg["NGINX_DIR"].rstrip("/")
    new, old = root + ".new", root + ".old"
    shutil.rmtree(new, ignore_errors=True)
    shutil.rmtree(old, ignore_errors=True)
    write_tree(new, render_all(config, cfg))
    ensure_cache_dirs(config, cfg)

    had_old = os.path.exists(root)
    if had_old:
        os.rename(root, old)
    os.rename(new, root)
    code, output = run(cfg["NGINX_TEST_CMD"])
    if code != 0:
        shutil.rmtree(root, ignore_errors=True)
        if had_old:
            os.rename(old, root)
        return "nginx -t failed: " + output[-1500:]
    code, output = run(cfg["NGINX_RELOAD_CMD"])
    shutil.rmtree(old, ignore_errors=True)
    if code != 0:
        return "nginx reload failed: " + output[-1500:]
    return None


# ----------------------------------------------------------------- purge

def cache_file(cache_dir: str, site_id: int, key: str) -> str:
    h = hashlib.md5(key.encode()).hexdigest()
    return os.path.join(cache_dir, str(site_id), h[-1], h[-3:-1], h)


def do_purge(item: dict, cfg: dict) -> int:
    sid = int(item["site_id"])
    base = os.path.join(cfg["CACHE_DIR"], str(sid))
    urls = item.get("urls") or []
    removed = 0
    if not urls:
        if os.path.isdir(base):
            for name in os.listdir(base):
                shutil.rmtree(os.path.join(base, name), ignore_errors=True)
                removed += 1
        return removed
    for url in urls:
        m = re.match(r"^https?://([^/]+)(/.*)?$", url)
        if not m:
            continue
        host, path = m.group(1).lower(), m.group(2) or "/"
        for scheme in ("http", "https"):
            p = cache_file(cfg["CACHE_DIR"], sid, f"{scheme}://{host}{path}")
            try:
                os.remove(p)
                removed += 1
            except FileNotFoundError:
                pass
    return removed


# ----------------------------------------------------------------- usage

def floor_hour(ts: str) -> str:
    dt = datetime.fromisoformat(ts)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc).replace(minute=0, second=0, microsecond=0).strftime("%Y-%m-%dT%H:00:00Z")


def _consume(path: str, pos: int, pending: dict, max_bytes: int) -> int:
    """Aggregate complete lines from path starting at pos; returns the new position."""
    with open(path, "rb") as f:
        f.seek(pos)
        chunk = f.read(max_bytes)
    end = chunk.rfind(b"\n")
    if end < 0:
        return pos
    for raw in chunk[: end + 1].splitlines():
        try:
            e = json.loads(raw)
            key = f"{e['h'].lower()}|{floor_hour(e['t'])}"
        except (ValueError, KeyError, TypeError):
            continue
        a = pending.setdefault(key, [0, 0, 0])
        a[0] += int(e.get("b") or 0)
        a[1] += 1
        if e.get("c") in ("HIT", "STALE", "UPDATING", "REVALIDATED"):
            a[2] += 1
    return pos + end + 1


def read_usage(state: dict, log_path: str, max_bytes: int = 200 * 1024 * 1024) -> None:
    """Consume new access-log lines and merge them into state['pending']."""
    try:
        st = os.stat(log_path)
    except FileNotFoundError:
        return
    pending = state.setdefault("pending", {})
    pos = state.get("log_pos", 0)
    if state.get("log_inode") not in (None, st.st_ino):
        # logrotate moved the file: finish the old one (now .1) before starting the new one
        rotated = log_path + ".1"
        try:
            if os.stat(rotated).st_ino == state["log_inode"]:
                _consume(rotated, pos, pending, max_bytes)
        except FileNotFoundError:
            pass
        pos = 0
    elif st.st_size < pos:
        pos = 0  # truncated
    state["log_pos"] = _consume(log_path, pos, pending, max_bytes)
    state["log_inode"] = st.st_ino
    if len(pending) > 50000:  # controller unreachable for a long time: keep newest
        for k in sorted(pending, key=lambda k: k.split("|")[1])[: len(pending) - 50000]:
            del pending[k]


def usage_items(pending: dict) -> list[dict]:
    items = []
    for key, (b, r, h) in pending.items():
        host, hour = key.split("|", 1)
        items.append({"host": host, "hour": hour, "bytes": b, "requests": r, "cache_hits": h})
    return items


# ----------------------------------------------------------------- controller

class Controller:
    def __init__(self, url: str, token: str):
        self.url = url.rstrip("/")
        self.token = token

    def call(self, method: str, path: str, body=None, headers=None, timeout=30):
        data = json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(self.url + path, data=data, method=method)
        req.add_header("Authorization", f"Bearer {self.token}")
        req.add_header("User-Agent", "pcdn-agent/1.0")
        if data is not None:
            req.add_header("Content-Type", "application/json")
        for k, v in (headers or {}).items():
            req.add_header(k, v)
        try:
            with urllib.request.urlopen(req, timeout=timeout) as r:
                raw = r.read()
                return r.status, dict(r.headers), (json.loads(raw) if raw else None)
        except urllib.error.HTTPError as e:
            if e.code == 304:
                return 304, dict(e.headers), None
            raise


# ----------------------------------------------------------------- main loop

def load_state(path: str) -> dict:
    try:
        with open(path) as f:
            return json.load(f)
    except (FileNotFoundError, ValueError):
        return {}


def save_state(path: str, state: dict):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        json.dump(state, f)
    os.replace(tmp, path)


class Agent:
    def __init__(self, cfg: dict):
        self.cfg = cfg
        self.ctl = Controller(cfg["CONTROLLER_URL"], cfg["EDGE_TOKEN"])
        self.state = load_state(cfg["STATE_FILE"])
        self.running = True
        self.last_usage = 0.0

    def sync_config(self):
        headers = {}
        if self.state.get("etag") and os.path.isdir(self.cfg["NGINX_DIR"]):
            headers["If-None-Match"] = self.state["etag"]
        code, hdrs, body = self.ctl.call("GET", "/edge/v1/config", headers=headers)
        if code == 304:
            return
        err = apply_config(body, self.cfg)
        if err:
            log.error(err)
            self.ctl.call("POST", "/edge/v1/heartbeat",
                          {"applied_version": self.state.get("version"), "error": err})
            return
        self.state["etag"] = hdrs.get("ETag") or hdrs.get("etag")
        self.state["version"] = body["version"]
        log.info("applied config %s (%d sites)", body["version"][:12], len(body.get("sites", [])))
        self.ctl.call("POST", "/edge/v1/heartbeat", {"applied_version": body["version"], "error": None})

    def sync_purges(self):
        after = int(self.state.get("purge_id", 0))
        _, _, items = self.ctl.call("GET", f"/edge/v1/purges?after={after}")
        if "purge_id" not in self.state:
            # first run: a fresh node has an empty cache, so skip history and remember where we are
            self.state["purge_id"] = items[-1]["id"] if items else 0
            return
        for it in items or []:
            n = do_purge(it, self.cfg)
            log.info("purge %s %s -> %d entries", it["domain"], it["urls"] or "ALL", n)
            self.state["purge_id"] = it["id"]

    def push_usage(self):
        read_usage(self.state, self.cfg["ACCESS_LOG"])
        items = usage_items(self.state.get("pending", {}))
        if items:
            self.ctl.call("POST", "/edge/v1/usage", {"items": items})
        self.state["pending"] = {}

    def tick(self):
        for step in (self.sync_config, self.sync_purges):
            try:
                step()
            except Exception as e:  # noqa: BLE001
                log.error("%s failed: %s", step.__name__, e)
        if time.time() - self.last_usage >= int(self.cfg["USAGE_INTERVAL"]):
            try:
                self.push_usage()
                self.last_usage = time.time()
            except Exception as e:  # noqa: BLE001 - pending usage stays in state for next try
                log.error("usage push failed: %s", e)
        save_state(self.cfg["STATE_FILE"], self.state)

    def loop(self):
        while self.running:
            self.tick()
            for _ in range(int(self.cfg["POLL_INTERVAL"])):
                if not self.running:
                    break
                time.sleep(1)


def main():
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    cfg = load_config(os.getenv("PCDN_CONFIG", "/etc/pcdn/agent.conf"))
    if not cfg["CONTROLLER_URL"] or not cfg["EDGE_TOKEN"]:
        log.error("CONTROLLER_URL and EDGE_TOKEN must be set in /etc/pcdn/agent.conf")
        sys.exit(1)
    agent = Agent(cfg)

    def stop(*_):
        agent.running = False

    signal.signal(signal.SIGTERM, stop)
    signal.signal(signal.SIGINT, stop)
    if len(sys.argv) > 1 and sys.argv[1] == "once":
        agent.tick()
        return
    agent.loop()


if __name__ == "__main__":
    main()
