"""Access (SPEC §18.2): protect path prefixes of a site with an e-mailed one-time code and/or an IP
allow list. Section `access`, plan feature `access`.

access_secret
-------------
32 random bytes per site, generated by the controller (when the section is first saved enabled, or
by ``POST /api/v1/sites/{d}/access/rotate``), stored encrypted in ``sites.integration_secrets``
(site_secrets key ``access``) and sent to the edges in the site config as **64 lowercase hex
characters** (``sites[].access.secret``). Every HMAC below is keyed with the **32 raw bytes**
(hex-decoded), never with the hex text. Rotating it invalidates every session cookie and code.

One-time code (``otp_code``; the edge recomputes it locally on verify)::

    window = floor(unix_seconds / 300)
    msg    = UTF-8 bytes of  "otp|" + app_id + "|" + lower(email) + "|" + decimal(window)
    d      = HMAC-SHA256(key = bytes.fromhex(access_secret), msg)            # 32 bytes
    off    = d[31] & 0x0f
    bin    = ((d[off] & 0x7f) << 24) | (d[off+1] << 16) | (d[off+2] << 8) | d[off+3]
    code   = decimal(bin mod 1_000_000), left-padded with "0" to 6 digits

(RFC 4226 dynamic truncation over HMAC-SHA256.) `lower` is ASCII lower-casing of the trimmed
address (only ASCII addresses are accepted). The verifier accepts the current and the previous
window. Test vectors: tests/test_wave10_access.py::VECTORS.

Usage (per host-hour item): ``access: {ok, fail, otp}`` (deltas, summed) and ``access_events:
[{t, app, email_hash, ok}]`` (≤50 per item; the controller keeps the newest 200 per site-hour and
``GET .../access/log`` returns the newest 200). ``email_hash`` is chosen by the edge (8..64 lowercase
hex; recommended: first 16 hex of HMAC-SHA256(raw access_secret, "email|" + lower(email))).
"""

import hashlib
import hmac
import json
import math
import re
import secrets as pysecrets
import time
from datetime import datetime, timedelta, timezone

from pydantic import BaseModel, Field, field_validator
from sqlalchemy import delete, func, select
from sqlalchemy.orm import Session

from . import sections, site_secrets
from .config import settings
from .models import AccessOtp, Site, UsageHourly, utcnow
from .validation import num
from .validation import obj as _obj

SECRET_KEY = "access"  # site_secrets key of access_secret
SECRET_RE = re.compile(r"^[0-9a-f]{64}$")
WINDOW_SECONDS = 300
CODE_DIGITS = 6
BIG = 10**18
EVENTS_PER_ITEM = 50
EVENTS_PER_ROW = 200
LOG_MAX = 200
LOG_DAYS = 30
EMAIL_HASH_RE = re.compile(r"^[0-9a-f]{8,64}$")
APP_ID_RE = re.compile(sections.ACCESS_APP_ID_RE)
COUNTERS = ("ok", "fail", "otp")


# ------------------------------------------------------------------ the reference code derivation

def otp_window(unix_seconds: float | None = None) -> int:
    return int((time.time() if unix_seconds is None else unix_seconds) // WINDOW_SECONDS)


def otp_code(secret_hex: str, app_id: str, email: str, window: int) -> str:
    """The 6-digit one-time code (see the module docstring for the exact byte formula)."""
    key = bytes.fromhex(secret_hex)
    msg = ("otp|" + app_id + "|" + email.strip().lower() + "|" + str(int(window))).encode("utf-8")
    d = hmac.new(key, msg, hashlib.sha256).digest()
    off = d[31] & 0x0F
    binary = ((d[off] & 0x7F) << 24) | (d[off + 1] << 16) | (d[off + 2] << 8) | d[off + 3]
    return str(binary % 10**CODE_DIGITS).zfill(CODE_DIGITS)


def verify_code(secret_hex: str, app_id: str, email: str, code: str, unix_seconds: float | None = None) -> bool:
    """Reference verifier (the edge does this): current or previous window, constant-time compare."""
    w = otp_window(unix_seconds)
    return any(hmac.compare_digest(otp_code(secret_hex, app_id, email, x), str(code)) for x in (w, w - 1))


def email_ref(email: str) -> str:
    """Site-independent reference of an address for the audit log and the rate limits (never the
    address itself): first 16 hex of SHA-256("pcdn-access-email|" + lower(email))."""
    return hashlib.sha256(("pcdn-access-email|" + email.strip().lower()).encode()).hexdigest()[:16]


# ------------------------------------------------------------------ secret

def new_secret() -> str:
    return pysecrets.token_hex(32)


def secret_of(site) -> str:
    try:
        v = site_secrets.get_secret(site, SECRET_KEY) or ""
    except Exception:  # noqa: BLE001 - undecryptable (lost DATA_ENCRYPTION_KEY)
        return ""
    return v if SECRET_RE.match(v) else ""


def ensure_secret(site) -> bool:
    if secret_of(site):
        return False
    site_secrets.set_secret(site, SECRET_KEY, new_secret())
    return True


def rotate(site) -> None:
    """A new access_secret (every session and pending code becomes invalid). Caller commits."""
    site_secrets.set_secret(site, SECRET_KEY, new_secret())


def after_write(site, value: dict) -> None:
    if value.get("enabled"):
        ensure_secret(site)


# ------------------------------------------------------------------ edge config

def edge_block(site, value: dict, feats: dict) -> dict:
    """`sites[].access`: enabled only with the plan's feature. While enabled with secret "" (the key
    could not be decrypted) the edge must fail closed: no session cookie or code can be valid."""
    enabled = bool(value.get("enabled") and feats.get("access") and value.get("apps"))
    return {
        "enabled": enabled,
        "apps": [{k: (list(a[k]) if isinstance(a[k], list) else a[k])
                  for k in ("id", "name", "paths", "methods", "emails", "ips", "session_hours")}
                 for a in value["apps"]] if enabled else [],
        "secret": secret_of(site) if enabled else "",
    }


def email_allowed(app: dict, email: str) -> bool:
    """Case-insensitive; an "@domain" entry matches exactly that domain (not its subdomains)."""
    email = email.strip().lower()
    domain = "@" + email.rpartition("@")[2]
    return any(e == email or (e.startswith("@") and e == domain) for e in app.get("emails") or [])


# ------------------------------------------------------------------ usage

class AccessUsage(BaseModel):
    ok: int = Field(0, ge=0, le=BIG, strict=True)
    fail: int = Field(0, ge=0, le=BIG, strict=True)
    otp: int = Field(0, ge=0, le=BIG, strict=True)


class AccessEvent(BaseModel):
    t: datetime
    app: str
    email_hash: str
    ok: bool = Field(strict=True)

    @field_validator("app")
    @classmethod
    def _app(cls, v):
        if not APP_ID_RE.match(v):
            raise ValueError("bad app id")
        return v

    @field_validator("email_hash")
    @classmethod
    def _hash(cls, v):
        if not EMAIL_HASH_RE.match(v):
            raise ValueError("bad email_hash")
        return v


def clean_events(v) -> list:
    """`access_events` of a usage item: malformed entries dropped (never a 422), at most 50."""
    if not isinstance(v, list):
        return []
    out = []
    for e in v:
        if len(out) >= EVENTS_PER_ITEM:
            break
        try:
            out.append(AccessEvent.model_validate(e))
        except Exception:  # noqa: BLE001 - informational data, never blocks billing
            continue
    return out


def _iso(dt: datetime) -> str:
    if dt.tzinfo is not None:
        dt = dt.astimezone(timezone.utc).replace(tzinfo=None)
    return dt.replace(microsecond=0).isoformat() + "Z"


def merge(current: dict, add: dict) -> None:
    """Merge `access` counters and `access_events` of one item into the per site-hour details."""
    ac = _obj(add.get("access"))
    if ac:
        dst = current.get("access")
        if not isinstance(dst, dict):
            dst = current["access"] = {}
        for k in COUNTERS:
            dst[k] = num(dst.get(k)) + num(ac.get(k))
    evs = add.get("access_events")
    if isinstance(evs, list) and evs:
        dst = current.get("access_events")
        if not isinstance(dst, list):
            dst = []
        for e in evs:
            if not isinstance(e, dict):
                continue
            t = e.get("t")
            if isinstance(t, datetime):
                t = _iso(t)
            if not isinstance(t, str):
                continue
            dst.append({"t": t[:32], "app": str(e.get("app"))[:32], "email_hash": str(e.get("email_hash"))[:64],
                        "ok": bool(e.get("ok"))})
        dst.sort(key=lambda x: x.get("t", ""))
        current["access_events"] = dst[-EVENTS_PER_ROW:]


def access_log(db: Session, site: Site, limit: int = LOG_MAX) -> dict:
    """Newest sign-ins / failed attempts reported by the edges (≤200) and 24 h / 30 d counters."""
    limit = max(1, min(limit, LOG_MAX))
    now = utcnow()
    since = now - timedelta(days=LOG_DAYS)
    day = now - timedelta(hours=24)
    events, last24, last30 = [], dict.fromkeys(COUNTERS, 0), dict.fromkeys(COUNTERS, 0)
    for hour, details in db.execute(select(UsageHourly.hour, UsageHourly.details).where(
            UsageHourly.site_id == site.id, UsageHourly.hour >= since)).all():
        try:
            d = json.loads(details or "{}")
        except ValueError:
            continue
        if not isinstance(d, dict):
            continue
        c = _obj(d.get("access"))
        for k in COUNTERS:
            last30[k] += num(c.get(k))
            if hour >= day:
                last24[k] += num(c.get(k))
        for e in d.get("access_events") or []:
            if isinstance(e, dict) and isinstance(e.get("t"), str):
                events.append({"t": e["t"], "app": e.get("app"), "email_hash": e.get("email_hash"),
                               "ok": bool(e.get("ok"))})
    events.sort(key=lambda e: e["t"], reverse=True)
    value = sections.get_section(site, "access")
    return {"enabled": bool(value["enabled"] and sections.features_of(site).get("access")),
            "apps": [a["id"] for a in value["apps"]],
            "last_24h": last24, "last_30d": last30, "events": events[:limit]}


# ------------------------------------------------------------------ OTP rate limits + mail

class RateLimited(Exception):
    def __init__(self, retry_after: int, scope: str):
        super().__init__(scope)
        self.retry_after = retry_after
        self.scope = scope


def check_rate(db: Session, site: Site, ref: str, now: datetime | None = None) -> None:
    """5 codes per e-mail address (all sites) and 50 per site in the last hour; RateLimited beyond."""
    now = now or utcnow()
    since = now - timedelta(hours=1)
    for scope, cond, limit in (("email", AccessOtp.email_hash == ref, settings.access_otp_per_email_hour),
                               ("site", AccessOtp.site_id == site.id, settings.access_otp_per_site_hour)):
        n, oldest = db.execute(select(func.count(AccessOtp.id), func.min(AccessOtp.at))
                               .where(cond, AccessOtp.at > since)).one()
        if n >= limit:
            wait = 60 if oldest is None else math.ceil((oldest + timedelta(hours=1) - now).total_seconds())
            raise RateLimited(max(1, wait), scope)


def note_sent(db: Session, site: Site, ref: str, now: datetime | None = None) -> None:
    now = now or utcnow()
    db.add(AccessOtp(site_id=site.id, email_hash=ref, at=now))
    # keep the table small: a day of history is plenty for hourly limits
    db.execute(delete(AccessOtp).where(AccessOtp.at < now - timedelta(days=1)))


def mail_text(domain: str, app_name: str, code: str) -> tuple[str, str]:
    """(subject, body) of the code e-mail, Persian first then English. Never the secret."""
    minutes = WINDOW_SECONDS // 60
    subject = f"کد ورود {domain} / Sign-in code for {domain}"
    body = (f"کد ورود شما به «{app_name}» در {domain}:\n\n    {code}\n\n"
            f"این کد حدود {minutes} تا {2 * minutes} دقیقه معتبر است. اگر شما درخواست نکرده‌اید، این پیام را "
            "نادیده بگیرید.\n\n"
            "--\n\n"
            f"Your sign-in code for \"{app_name}\" on {domain}:\n\n    {code}\n\n"
            f"It is valid for about {minutes} to {2 * minutes} minutes. If you did not request it, ignore this "
            "e-mail.\n")
    return subject, body
