"""Waiting room (SPEC §18.1): section `waiting_room`, plan feature `waiting_room`.

Edge config (per site, ``sites[].waiting_room``)::

    {"enabled": bool, "mode": "queue"|"off", "paths": ["/", ...], "max_active": n, "node_max": n,
     "session_minutes": n, "queue_page": {"title_fa", "title_en", "message_fa", "message_en"},
     "bypass": {"verified_bots": bool, "paths": [...], "ips": ["cidr", ...]}, "secret": "<64 hex>"}

* ``enabled`` is the effective switch: section enabled, mode queue, the plan's feature, the site
  active and a readable ``wr_secret``; when false the edge ignores the rest.
* ``node_max = ceil(max_active / n)`` where n = the healthy enabled edges answering for the site in
  DNS (``dnsbuild.dns_edges`` over the online edges: the site's edge group, shed edges left out while
  their pool keeps another edge, every online edge in fail-open), at least 1. Health/load only.
* ``secret`` is the site's ``wr_secret``: 32 random bytes as 64 lowercase hex characters, generated by
  the controller when the section is first saved enabled, stored encrypted in
  ``sites.integration_secrets`` (site_secrets key ``waiting_room``). The edge signs its ``__pcdn_wr``
  cookie with HMAC-SHA256 keyed by the 32 raw bytes (hex-decoded); the cookie format is edge-only.

Usage (per host-hour item): ``waiting_room: {admitted, queued, max_wait_s, peak_active}``;
admitted/queued are deltas (summed), max_wait_s/peak_active are hour-to-date maxima (merged by max).
Heartbeat: ``waiting_room: {"<site domain>": {"active": n, "queued": n}}`` (≤1000 sites; junk entries
dropped, never a 422).
"""

import json
import math
import re
import secrets as pysecrets
from datetime import datetime, timedelta

from pydantic import BaseModel, Field
from sqlalchemy import select
from sqlalchemy.orm import Session

from . import dnsbuild, sections, site_secrets
from .config import settings
from .models import Edge, Site, UsageHourly, utcnow
from .validation import num
from .validation import obj as _obj

SECRET_KEY = "waiting_room"  # site_secrets key of wr_secret
SECRET_RE = re.compile(r"^[0-9a-f]{64}$")
BIG = 10**18
COUNTERS_SUM = ("admitted", "queued")
COUNTERS_MAX = ("max_wait_s", "peak_active")
HEARTBEAT_MAX_SITES = 1000
HEARTBEAT_MAX_VALUE = 1_000_000_000
MAX_HOURS = 744
DOMAIN_RE = re.compile(r"^(?=.{1,253}$)[a-z0-9_](?:[a-z0-9_-]{0,61}[a-z0-9])?(?:\.[a-z0-9_](?:[a-z0-9_-]{0,61}"
                       r"[a-z0-9])?)*$")


class WaitingRoomUsage(BaseModel):
    """`waiting_room` of one host-hour usage item; unknown keys are ignored, bad counters -> 422."""
    admitted: int = Field(0, ge=0, le=BIG, strict=True)
    queued: int = Field(0, ge=0, le=BIG, strict=True)
    max_wait_s: int = Field(0, ge=0, le=7 * 86400, strict=True)
    peak_active: int = Field(0, ge=0, le=HEARTBEAT_MAX_VALUE, strict=True)


# ------------------------------------------------------------------ secret

def new_secret() -> str:
    return pysecrets.token_hex(32)


def secret_of(site) -> str:
    """The decrypted wr_secret ("" when none / unreadable)."""
    try:
        v = site_secrets.get_secret(site, SECRET_KEY) or ""
    except Exception:  # noqa: BLE001 - undecryptable (lost DATA_ENCRYPTION_KEY)
        return ""
    return v if SECRET_RE.match(v) else ""


def ensure_secret(site) -> bool:
    """Generate the wr_secret when the site has none (or an unreadable one). Caller holds the site
    lock and commits. True when a new secret was stored."""
    if secret_of(site):
        return False
    site_secrets.set_secret(site, SECRET_KEY, new_secret())
    return True


def after_write(site, value: dict) -> None:
    """PUT waiting_room: an enabled section gets its secret now (edges never wait for one)."""
    if value.get("enabled"):
        ensure_secret(site)


# ------------------------------------------------------------------ edge config

def serving_edges(site, online: list) -> int:
    """How many healthy enabled edges serve the site (what DNS answers with), at least 1."""
    return max(1, len(dnsbuild.dns_edges(site, online)))


def node_max(max_active: int, serving: int) -> int:
    return max(1, math.ceil(max_active / max(1, serving)))


def effective(site, value: dict, feats: dict) -> bool:
    return bool(value.get("enabled") and value.get("mode") == "queue" and feats.get("waiting_room")
                and getattr(site, "effective_status", "active") == "active")


def edge_block(site, value: dict, feats: dict, serving: int) -> dict:
    secret = secret_of(site)
    return {
        "enabled": effective(site, value, feats) and bool(secret),
        "mode": value["mode"],
        "paths": list(value["paths"]),
        "max_active": value["max_active"],
        "node_max": node_max(value["max_active"], serving),
        "session_minutes": value["session_minutes"],
        "queue_page": dict(value["queue_page"]),
        "bypass": {"verified_bots": value["bypass"]["verified_bots"], "paths": list(value["bypass"]["paths"]),
                   "ips": list(value["bypass"]["ips"])},
        "secret": secret,
    }


# ------------------------------------------------------------------ usage

def merge(current, add) -> dict:
    """Merge one `waiting_room` usage block into the stored per site-hour one."""
    dst = dict(current) if isinstance(current, dict) else {}
    src = _obj(add)
    for k in COUNTERS_SUM:
        dst[k] = num(dst.get(k)) + num(src.get(k))
    for k in COUNTERS_MAX:
        dst[k] = max(num(dst.get(k)), num(src.get(k)))
    return dst


# ------------------------------------------------------------------ heartbeat

def clean_heartbeat(v) -> dict[str, dict]:
    """{domain: {active, queued}} from a heartbeat; junk entries dropped, at most 1000 sites."""
    if not isinstance(v, dict):
        return {}
    out = {}
    for k, c in v.items():
        if len(out) >= HEARTBEAT_MAX_SITES:
            break
        if not isinstance(k, str) or not isinstance(c, dict):
            continue
        d = k.strip().lower().rstrip(".")
        if not DOMAIN_RE.match(d):
            continue
        vals = {}
        for f in ("active", "queued"):
            x = c.get(f, 0)
            if isinstance(x, bool) or not isinstance(x, int) or not 0 <= x <= HEARTBEAT_MAX_VALUE:
                vals = None
                break
            vals[f] = x
        if vals is not None:
            out[d] = vals
    return out


def record_heartbeat(edge: Edge, counters: dict[str, dict], now: datetime) -> None:
    edge.waiting_room = json.dumps({"at": now.isoformat() + "Z", "sites": counters}, sort_keys=True)


def _live(db: Session, domain: str, now: datetime) -> tuple[int, int, int]:
    """(active, queued, reporting edges) of the site summed over fresh heartbeats."""
    cutoff = now - timedelta(seconds=settings.edge_offline_seconds)
    active = queued = n = 0
    for (raw,) in db.execute(select(Edge.waiting_room).where(Edge.enabled.is_(True), Edge.waiting_room.is_not(None),
                                                            Edge.last_seen_at >= cutoff)).all():
        try:
            doc = json.loads(raw or "{}")
            at = datetime.fromisoformat(str(doc.get("at", "")).rstrip("Z"))
        except (ValueError, TypeError, AttributeError):
            continue
        if at < cutoff:
            continue
        c = _obj(_obj(doc.get("sites")).get(domain))
        if c:
            active += num(c.get("active"))
            queued += num(c.get("queued"))
            n += 1
    return active, queued, n


# ------------------------------------------------------------------ stats

def _zero() -> dict:
    return {"admitted": 0, "queued": 0, "max_wait_s": 0, "peak_active": 0}


def stats(db: Session, site: Site, hours: int = 24) -> dict:
    """GET /sites/{d}/waiting-room: effective state, the live estimate from the edges' heartbeats and
    the hourly counters (summed over edges; max_wait_s = max, peak_active = sum of per-edge peaks)."""
    from .services import online_edges

    now = utcnow()
    hour_now = now.replace(minute=0, second=0, microsecond=0)
    since = hour_now - timedelta(hours=hours - 1)
    value = sections.get_section(site, "waiting_room")
    feats = sections.features_of(site)
    buckets: dict[str, dict] = {}
    for hour, details in db.execute(select(UsageHourly.hour, UsageHourly.details).where(
            UsageHourly.site_id == site.id, UsageHourly.hour >= since)).all():
        try:
            wr = json.loads(details or "{}").get("waiting_room")
        except (ValueError, AttributeError):
            continue
        if not isinstance(wr, dict):
            continue
        key = hour.strftime("%Y-%m-%dT%H:00:00Z")
        b = buckets.setdefault(key, _zero())
        b["admitted"] += num(wr.get("admitted"))
        b["queued"] += num(wr.get("queued"))
        b["max_wait_s"] = max(b["max_wait_s"], num(wr.get("max_wait_s")))
        b["peak_active"] += num(wr.get("peak_active"))
    series, t = [], since
    while t <= hour_now:
        key = t.strftime("%Y-%m-%dT%H:00:00Z")
        series.append({"t": key, **buckets.get(key, _zero())})
        t += timedelta(hours=1)
    active, queued, reporting = _live(db, site.domain, now)
    serving = serving_edges(site, online_edges(db))
    return {
        "enabled": effective(site, value, feats),
        "feature": bool(feats.get("waiting_room")),
        "mode": value["mode"],
        "max_active": value["max_active"],
        "serving_edges": serving,
        "node_max": node_max(value["max_active"], serving),
        "active_estimate": active,
        "queued_estimate": queued,
        "edges_reporting": reporting,
        "last_hour": {k: v for k, v in series[-1].items() if k != "t"},
        "hours": hours,
        "hourly": series,
    }
